<?php
if (!defined('YUYUN_ROOT')) {
    define('YUYUN_ROOT', dirname(__DIR__));
}

// 8 种国际语言
$availableLanguages = [
    'zh'    => ['name' => '中文',        'flag' => '🇨🇳'],
    'en'    => ['name' => 'English',     'flag' => '🇺🇸'],
    'ja'    => ['name' => '日本語',      'flag' => '🇯🇵'],
    'ko'    => ['name' => '한국어',      'flag' => '🇰🇷'],
    'zh-TW' => ['name' => '繁體中文',    'flag' => '🇹🇼'],
    'ru'    => ['name' => 'Русский',     'flag' => '🇷🇺'],
    'fr'    => ['name' => 'Français',    'flag' => '🇫🇷'],
    'de'    => ['name' => 'Deutsch',     'flag' => '🇩🇪'],
];

$langCodes = array_keys($availableLanguages);

function detectLang(): string {
    global $langCodes;
    if (isset($_GET['lang']) && in_array($_GET['lang'], $langCodes, true)) {
        setcookie('lang', $_GET['lang'], time()+86400*365, '/');
        return $_GET['lang'];
    }
    if (isset($_COOKIE['lang']) && in_array($_COOKIE['lang'], $langCodes, true)) {
        return $_COOKIE['lang'];
    }
    if (session_status() === PHP_SESSION_ACTIVE && isset($_SESSION['lang']) && in_array($_SESSION['lang'], $langCodes, true)) {
        return $_SESSION['lang'];
    }
    // 浏览器自动检测
    $accept = $_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '';
    if ($accept) {
        foreach (explode(',', $accept) as $pref) {
            $code = strtolower(trim(explode(';', $pref)[0]));
            $map = ['zh-cn'=>'zh','zh-sg'=>'zh','zh-hk'=>'zh-TW','zh-tw'=>'zh-TW','ja'=>'ja','ko'=>'ko','ru'=>'ru','fr'=>'fr','de'=>'de','en'=>'en'];
            if (isset($map[$code])) return $map[$code];
            $short = substr($code, 0, 2);
            $map2 = ['zh'=>'zh','ja'=>'ja','ko'=>'ko','ru'=>'ru','fr'=>'fr','de'=>'de','en'=>'en'];
            if (isset($map2[$short])) return $map2[$short];
        }
    }
    return 'zh';
}

$_SESSION['lang'] = detectLang();
$currentLang = $_SESSION['lang'];

$translations = [
    'zh' => [
        'home' => '首页', 'about' => '关于我们', 'company' => '公司简介', 'products' => '产品介绍',
        'partners' => '合作伙伴', 'contact' => '联系我们', 'intl' => '国际版官网',
        'user_center' => '用户中心', 'admin' => '后台', 'login' => '登录', 'logout' => '退出',
        'register' => '注册', 'submit' => '提交', 'save' => '保存', 'cancel' => '取消',
        'edit' => '编辑', 'delete' => '删除', 'search' => '搜索', 'phone' => '电话', 'email' => '邮箱',
        'password' => '密码', 'confirm_password' => '确认密码', 'nickname' => '昵称', 'welcome' => '欢迎',
        'back_to_top' => '返回顶部', 'online_support' => '在线客服', 'learn_more' => '立即了解',
        'view_products' => '查看产品', 'detail' => '了解详情', 'copyright' => '版权所有',
        'beian' => '备案号', 'police' => '公安网备案号', 'sales_phone' => '销售电话',
        'login_welcome' => '欢迎回来', 'login_subtitle' => '登录语云科技用户中心',
        'register_account' => '创建账号', 'register_subtitle' => '注册后即可提交工单与建议',
        'verify_login' => '邮箱验证码登录', 'verify_subtitle' => '无需密码，验证码 5 分钟内有效',
        'send_code' => '发送验证码', 'verify_code' => '验证码', 'my_tickets' => '我的工单',
        'feedback' => '建议/举报', 'profile' => '个人资料', 'notifications' => '消息通知',
        'no_notifications' => '暂无消息', 'mark_read' => '标记已读', 'system_notice' => '系统公告',
        'theme_light' => '浅色模式', 'theme_dark' => '深色模式', 'language' => '语言',
        'banner_default' => '欢迎来到语云科技官网！',
        'products_title' => '业务与产品', 'products_sub' => '覆盖云计算、网络安全、企业服务的全栈解决方案',
        'partners_title' => '我们与以下企业 / 组织携手共进', 'map_title' => '公司分布',
        'map_sub' => '全球节点布局，保障业务稳定低延迟', 'cert_title' => '资质证照',
        'cert_sub' => '合规经营，值得信赖', 'team_title' => '核心团队',
        'team_sub' => '来自全球顶尖科技与互联网企业', 'phone_consult' => '电话咨询',
        'later' => '稍后再说', 'welcome_to' => '欢迎来到', 'quick_entry' => '快捷入口',
        'new_ticket' => '提交工单', 'ticket_title' => '标题', 'ticket_category' => '分类',
        'ticket_content' => '内容', 'status_open' => '处理中', 'status_closed' => '已关闭',
        'reply' => '回复', 'close_ticket' => '关闭工单', 'reopen' => '重新打开',
        'feedback_type' => '类型', 'suggestion' => '产品建议', 'report' => '违规举报',
        'complaint' => '投诉', 'history' => '历史记录', 'contact_info' => '联系方式（选填）',
        'feedback_content' => '内容', 'submit_success' => '提交成功，感谢您的反馈',
        'field_required' => '不能为空', 'no_image_tip' => '暂无图片，请前往后台上传资质证照。',
        'click_mask_close' => '点击遮罩关闭', 'cert_preview' => '证照预览',
        'business_license' => '营业执照', 'ev_license' => '电子增值服务产业证',
        'security_cert' => '信息安全等级保护', 'trust_cert' => '可信云服务认证',
        'issued_by' => '工商行政管理机关核发', 'telecom_license' => '电信与信息服务业务经营许可',
        'level3_cert' => '三级等保认证', 'cloud_eval' => '云计算服务能力评估',
        'about_title' => '关于语云', 'company_title' => '公司简介', 'contact_title' => '联系我们',
        'partners_title_page' => '合作伙伴', 'products_title_page' => '产品介绍',
        'company_name' => '公司名称', 'company_short' => '公司简称', 'company_address' => '公司地址',
        'company_phone' => '公司电话', 'company_group' => '官方群聊', 'company_intro' => '公司简介',
        'address' => '地址', 'select_language' => '选择语言',
        'page_about' => '关于我们', 'page_company' => '公司简介', 'page_contact' => '联系我们', 'page_partners' => '合作伙伴', 'page_products' => '产品介绍', 'page_login' => '用户登录', 'page_register' => '用户注册', 'page_verify' => '邮箱验证码登录',
        'about_sub' => '了解语云科技的使命与价值观', 'company_sub' => '发展历程 · 企业文化 · 核心优势', 'contact_sub' => '期待与您携手合作', 'partners_sub' => '携手行业领袖，共建生态未来', 'products_sub' => '全栈云产品与数字化解决方案',
        'your_name' => '您的姓名', 'contact_email' => '联系邮箱', 'message_content' => '留言内容', 'submit_message' => '提交留言', 'contact_success' => '感谢您的留言，我们会尽快与您联系！', 'fill_complete' => '请填写完整信息',
        'company_desc' => '是一家全球化云计算与数字化服务提供商。我们依托自建数据中心与全球合作伙伴网络，为企业客户提供云服务器、裸金属、CDN 加速、DDoS 防护、企业邮箱以及 IDC 财务系统授权等一站式解决方案。',
        'history_title' => '发展历程', 'culture_title' => '企业文化', 'advantages_title' => '核心优势', 'culture_desc' => '我们坚持"客户为先、技术驱动、全球协作"的价值观，致力于让每一家企业都能享受到稳定、安全、普惠的云计算能力。',
        'global_network' => '全球网络', 'security_protection' => '安全防护', 'support_247' => '7×24 支持', 'global_network_desc' => '多地域、多运营商骨干网络，智能调度。', 'security_protection_desc' => 'T 级 DDoS 清洗与 Web 应用防火墙。', 'support_247_desc' => '专业技术团队全天候响应。',
        'password_login' => '密码登录', 'code_login' => '邮箱验证码登录', 'no_account' => '还没有账号？', 'register_now' => '立即注册', 'has_account' => '已有账号？', 'login_now' => '立即登录',
        'email_invalid' => '邮箱格式不正确', 'password_short' => '密码至少 6 位', 'password_mismatch' => '两次密码不一致', 'email_exists' => '该邮箱已注册', 'login_success' => '登录成功', 'email_or_password_error' => '邮箱或密码错误', 'email_not_verified' => '邮箱尚未验证，请使用邮箱验证码登录完成验证', 'register_success' => '注册成功', 'register_success_verify' => '注册成功，请使用邮箱验证码登录完成验证',
        'code_sent' => '验证码已发送，请查收邮箱', 'code_error' => '验证码错误或已过期', 'current_password' => '当前密码（修改密码时填写）', 'new_password' => '新密码', 'password_error' => '当前密码错误', 'profile_updated' => '资料已更新', 'profile_password_updated' => '资料与密码已更新',
        'ticket_submitted' => '工单已提交', 'ticket_closed' => '工单已关闭', 'fill_title_content' => '请填写标题和内容', 'ticket_not_exist' => '工单不存在', 'new_ticket_form' => '提交新工单', 'reply_placeholder' => '回复内容', 'close_ticket_confirm' => '确定关闭该工单？', 'back_to_list' => '返回工单列表', 'ticket_records' => '工单记录', 'view_detail' => '查看', 'ticket_question' => '问题描述',
        'cat_technical' => '技术咨询', 'cat_after_sales' => '售后问题', 'cat_billing' => '账单疑问', 'cat_complaint' => '投诉建议', 'cat_other' => '其他',
        'feedback_submitted' => '提交成功，感谢您的反馈', 'fill_content' => '请填写内容', 'official_reply' => '官方回复', 'official_tag' => '官方', 'visit_official' => '访问官网', 'official_group' => '官方群聊', 'international_site' => '国际版官网',
        'product_detail' => '产品详情', 'all_read_confirm' => '全部标记为已读？', 'phone_label' => '手机',
    ],
    'en' => [
        'home' => 'Home', 'about' => 'About', 'company' => 'Company', 'products' => 'Products',
        'partners' => 'Partners', 'contact' => 'Contact', 'intl' => 'International',
        'user_center' => 'User Center', 'admin' => 'Admin', 'login' => 'Login', 'logout' => 'Logout',
        'register' => 'Register', 'submit' => 'Submit', 'save' => 'Save', 'cancel' => 'Cancel',
        'edit' => 'Edit', 'delete' => 'Delete', 'search' => 'Search', 'phone' => 'Phone', 'email' => 'Email',
        'password' => 'Password', 'confirm_password' => 'Confirm Password', 'nickname' => 'Nickname', 'welcome' => 'Welcome',
        'back_to_top' => 'Back to Top', 'online_support' => 'Support', 'learn_more' => 'Learn More',
        'view_products' => 'View Products', 'detail' => 'Details', 'copyright' => 'All Rights Reserved',
        'beian' => 'ICP', 'police' => 'Police Filing', 'sales_phone' => 'Sales',
        'login_welcome' => 'Welcome Back', 'login_subtitle' => 'Login to YuYun user center',
        'register_account' => 'Create Account', 'register_subtitle' => 'Register to submit tickets & feedback',
        'verify_login' => 'Email Code Login', 'verify_subtitle' => 'No password needed, code valid for 5 minutes',
        'send_code' => 'Send Code', 'verify_code' => 'Verification Code', 'my_tickets' => 'My Tickets',
        'feedback' => 'Feedback', 'profile' => 'Profile', 'notifications' => 'Notifications',
        'no_notifications' => 'No notifications', 'mark_read' => 'Mark Read', 'system_notice' => 'System Notice',
        'theme_light' => 'Light Mode', 'theme_dark' => 'Dark Mode', 'language' => 'Language',
        'banner_default' => 'Welcome to YuYun Technology!',
        'products_title' => 'Business & Products', 'products_sub' => 'Full-stack solutions covering cloud computing, security & enterprise services',
        'partners_title' => 'We work together with these enterprises & organizations', 'map_title' => 'Global Distribution',
        'map_sub' => 'Global node layout ensuring stable & low-latency business', 'cert_title' => 'Qualifications',
        'cert_sub' => 'Compliant operations, trustworthy', 'team_title' => 'Core Team',
        'team_sub' => 'From top global tech & internet companies', 'phone_consult' => 'Call Us',
        'later' => 'Later', 'welcome_to' => 'Welcome to', 'quick_entry' => 'Quick Access',
        'new_ticket' => 'New Ticket', 'ticket_title' => 'Title', 'ticket_category' => 'Category',
        'ticket_content' => 'Content', 'status_open' => 'Open', 'status_closed' => 'Closed',
        'reply' => 'Reply', 'close_ticket' => 'Close Ticket', 'reopen' => 'Reopen',
        'feedback_type' => 'Type', 'suggestion' => 'Suggestion', 'report' => 'Report',
        'complaint' => 'Complaint', 'history' => 'History', 'contact_info' => 'Contact (optional)',
        'feedback_content' => 'Content', 'submit_success' => 'Submitted successfully, thank you for your feedback',
        'field_required' => 'cannot be empty', 'no_image_tip' => 'No image available, please upload in admin panel.',
        'click_mask_close' => 'Click overlay to close', 'cert_preview' => 'Certificate Preview',
        'business_license' => 'Business License', 'ev_license' => 'EV Service License',
        'security_cert' => 'Information Security Level Protection', 'trust_cert' => 'Trusted Cloud Certification',
        'issued_by' => 'Issued by industry & commerce administration', 'telecom_license' => 'Telecom & information service license',
        'level3_cert' => 'Level 3 Security Certification', 'cloud_eval' => 'Cloud computing service capability assessment',
        'about_title' => 'About YuYun', 'company_title' => 'Company Profile', 'contact_title' => 'Contact Us',
        'partners_title_page' => 'Partners', 'products_title_page' => 'Products',
        'company_name' => 'Company Name', 'company_short' => 'Short Name', 'company_address' => 'Address',
        'company_phone' => 'Phone', 'company_group' => 'Group Chat', 'company_intro' => 'Introduction',
        'address' => 'Address', 'select_language' => 'Select Language',
        'page_about' => 'About Us', 'page_company' => 'Company', 'page_contact' => 'Contact', 'page_partners' => 'Partners', 'page_products' => 'Products', 'page_login' => 'Login', 'page_register' => 'Register', 'page_verify' => 'Email Code Login',
        'about_sub' => 'Learn about YuYun mission and values', 'company_sub' => 'History · Culture · Advantages', 'contact_sub' => 'Looking forward to working with you', 'partners_sub' => 'With industry leaders, building the future', 'products_sub' => 'Full-stack cloud products & solutions',
        'your_name' => 'Your Name', 'contact_email' => 'Contact Email', 'message_content' => 'Message', 'submit_message' => 'Send Message', 'contact_success' => 'Thank you for your message, we will contact you soon!', 'fill_complete' => 'Please fill in all fields',
        'company_desc' => 'is a global cloud computing and digital service provider. Relying on self-built data centers and a global partner network, we provide enterprise customers with cloud servers, bare metal, CDN acceleration, DDoS protection, enterprise email and IDC financial system licensing in one-stop solutions.',
        'history_title' => 'History', 'culture_title' => 'Culture', 'advantages_title' => 'Core Advantages', 'culture_desc' => 'We adhere to the values of "customer first, technology driven, global collaboration", and are committed to enabling every enterprise to enjoy stable, secure and inclusive cloud computing.',
        'global_network' => 'Global Network', 'security_protection' => 'Security', 'support_247' => '24/7 Support', 'global_network_desc' => 'Multi-region, multi-carrier backbone, smart scheduling.', 'security_protection_desc' => 'T-level DDoS cleaning & WAF.', 'support_247_desc' => 'Professional team on call 24/7.',
        'password_login' => 'Password Login', 'code_login' => 'Email Code Login', 'no_account' => 'No account?', 'register_now' => 'Register', 'has_account' => 'Have an account?', 'login_now' => 'Login',
        'email_invalid' => 'Invalid email format', 'password_short' => 'Password must be at least 6 characters', 'password_mismatch' => 'Passwords do not match', 'email_exists' => 'Email already registered', 'login_success' => 'Login successful', 'email_or_password_error' => 'Email or password incorrect', 'email_not_verified' => 'Email not verified, please use email code login to verify', 'register_success' => 'Registration successful', 'register_success_verify' => 'Registered, please use email code login to verify',
        'code_sent' => 'Code sent, please check your email', 'code_error' => 'Code incorrect or expired', 'current_password' => 'Current Password (for password change)', 'new_password' => 'New Password', 'password_error' => 'Current password incorrect', 'profile_updated' => 'Profile updated', 'profile_password_updated' => 'Profile and password updated',
        'ticket_submitted' => 'Ticket submitted', 'ticket_closed' => 'Ticket closed', 'fill_title_content' => 'Please fill in title and content', 'ticket_not_exist' => 'Ticket does not exist', 'new_ticket_form' => 'New Ticket', 'reply_placeholder' => 'Reply content', 'close_ticket_confirm' => 'Close this ticket?', 'back_to_list' => 'Back to tickets', 'ticket_records' => 'Ticket Records', 'view_detail' => 'View', 'ticket_question' => 'Description',
        'cat_technical' => 'Technical', 'cat_after_sales' => 'After Sales', 'cat_billing' => 'Billing', 'cat_complaint' => 'Complaint', 'cat_other' => 'Other',
        'feedback_submitted' => 'Submitted successfully, thank you', 'fill_content' => 'Please fill in content', 'official_reply' => 'Official Reply', 'official_tag' => 'Official', 'visit_official' => 'Visit Website', 'official_group' => 'Group Chat', 'international_site' => 'International Site',
        'product_detail' => 'Product Details', 'all_read_confirm' => 'Mark all as read?', 'phone_label' => 'Phone',
    ],
    'ja' => [
        'home' => 'ホーム', 'about' => 'について', 'company' => '会社概要', 'products' => '製品',
        'partners' => 'パートナー', 'contact' => 'お問い合わせ', 'intl' => '国際版',
        'user_center' => 'ユーザーセンター', 'admin' => '管理', 'login' => 'ログイン', 'logout' => 'ログアウト',
        'register' => '登録', 'submit' => '送信', 'save' => '保存', 'cancel' => 'キャンセル',
        'edit' => '編集', 'delete' => '削除', 'search' => '検索', 'phone' => '電話', 'email' => 'メール',
        'password' => 'パスワード', 'confirm_password' => 'パスワード確認', 'nickname' => 'ニックネーム', 'welcome' => 'ようこそ',
        'back_to_top' => 'トップへ', 'online_support' => 'サポート', 'learn_more' => '詳しく見る',
        'view_products' => '製品を見る', 'detail' => '詳細', 'copyright' => 'All Rights Reserved',
        'beian' => 'ICP', 'police' => 'Police Filing', 'sales_phone' => '営業電話',
        'login_welcome' => 'おかえりなさい', 'login_subtitle' => '語雲科技ユーザーセンターへログイン',
        'register_account' => 'アカウント作成', 'register_subtitle' => '登録してチケットとフィードバックを送信',
        'verify_login' => 'メールコードログイン', 'verify_subtitle' => 'パスワード不要、5分間有効',
        'send_code' => 'コード送信', 'verify_code' => '認証コード', 'my_tickets' => 'マイチケット',
        'feedback' => 'フィードバック', 'profile' => 'プロフィール', 'notifications' => '通知',
        'no_notifications' => '通知なし', 'mark_read' => '既読にする', 'system_notice' => 'システム通知',
        'theme_light' => 'ライトモード', 'theme_dark' => 'ダークモード', 'language' => '言語',
        'banner_default' => '語雲科技へようこそ！',
        'products_title' => 'ビジネスと製品', 'products_sub' => 'クラウド、セキュリティ、企業サービスのフルスタックソリューション',
        'partners_title' => '以下の企業・組織と協力しています', 'map_title' => 'グローバル展開',
        'map_sub' => '世界中のノードで安定した低遅延を実現', 'cert_title' => '資格認定',
        'cert_sub' => 'コンプライアンス経営、信頼性', 'team_title' => 'コアチーム',
        'team_sub' => '世界トップクラスの技術・インターネット企業から', 'phone_consult' => '電話相談',
        'later' => '後で', 'welcome_to' => 'ようこそ', 'quick_entry' => 'クイックアクセス',
        'new_ticket' => '新規チケット', 'ticket_title' => 'タイトル', 'ticket_category' => 'カテゴリ',
        'ticket_content' => '内容', 'status_open' => '処理中', 'status_closed' => 'クローズ',
        'reply' => '返信', 'close_ticket' => 'クローズ', 'reopen' => '再開',
        'feedback_type' => 'タイプ', 'suggestion' => '提案', 'report' => '通報',
        'complaint' => '苦情', 'history' => '履歴', 'contact_info' => '連絡先（任意）',
        'feedback_content' => '内容', 'submit_success' => '送信成功、フィードバックありがとうございます',
        'field_required' => 'は必須です', 'no_image_tip' => '画像がありません。管理画面からアップロードしてください。',
        'click_mask_close' => 'オーバーレイをクリックして閉じる', 'cert_preview' => '証明書プレビュー',
        'business_license' => '営業許可証', 'ev_license' => '付加価値サービス許可証',
        'security_cert' => '情報セキュリティ等保護', 'trust_cert' => '信頼できるクラウド認定',
        'issued_by' => '工商管理局発行', 'telecom_license' => '電気通信サービス許可',
        'level3_cert' => 'レベル3等保護認定', 'cloud_eval' => 'クラウドサービス能力評価',
        'about_title' => '語雲について', 'company_title' => '会社概要', 'contact_title' => 'お問い合わせ',
        'partners_title_page' => 'パートナー', 'products_title_page' => '製品',
        'company_name' => '会社名', 'company_short' => '略称', 'company_address' => '住所',
        'company_phone' => '電話', 'company_group' => 'グループチャット', 'company_intro' => '紹介',
        'address' => '住所', 'select_language' => '言語を選択',
        'page_about' => 'について', 'page_company' => '会社概要', 'page_contact' => 'お問い合わせ', 'page_partners' => 'パートナー', 'page_products' => '製品', 'page_login' => 'ログイン', 'page_register' => '登録', 'page_verify' => 'メールコードログイン',
        'about_sub' => '語雲科技の使命と価値観について', 'company_sub' => '沿革 · 企業文化 · コア優位性', 'contact_sub' => '共に協力できることを楽しみにしています', 'partners_sub' => '業界リーダーと共に未来を構築', 'products_sub' => 'フルスタックのクラウド製品とソリューション',
        'your_name' => 'お名前', 'contact_email' => '連絡先メール', 'message_content' => 'メッセージ', 'submit_message' => 'メッセージ送信', 'contact_success' => 'お問い合わせありがとうございます。早急にご連絡いたします！', 'fill_complete' => 'すべての項目を入力してください',
        'company_desc' => 'はグローバルなクラウドコンピューティングとデジタルサービスプロバイダーです。自社データセンターとグローバルパートナーネットワークにより、クラウドサーバー、ベアメタル、CDNアクセラレーション、DDoS保護、企業メール、IDC財務システムライセンスをワンストップで提供します。',
        'history_title' => '沿革', 'culture_title' => '企業文化', 'advantages_title' => 'コア優位性', 'culture_desc' => '「顧客第一、技術駆動、グローバル協力」の価値観を堅持し、すべての企業が安定した安全で普遍的なクラウドコンピューティングを享受できるよう取り組んでいます。',
        'global_network' => 'グローバルネットワーク', 'security_protection' => 'セキュリティ', 'support_247' => '24/7サポート', 'global_network_desc' => '多地域・多キャリアバックボーン、スマートスケジューリング。', 'security_protection_desc' => 'T級DDoSクリーニングとWAF。', 'support_247_desc' => 'プロフェッショナルチームが24時間対応。',
        'password_login' => 'パスワードログイン', 'code_login' => 'メールコードログイン', 'no_account' => 'アカウントなし？', 'register_now' => '登録', 'has_account' => 'アカウントあり？', 'login_now' => 'ログイン',
        'email_invalid' => 'メール形式が不正です', 'password_short' => 'パスワードは6文字以上必要です', 'password_mismatch' => 'パスワードが一致しません', 'email_exists' => 'メールは既に登録済みです', 'login_success' => 'ログイン成功', 'email_or_password_error' => 'メールまたはパスワードが不正です', 'email_not_verified' => 'メール未確認、メールコードログインで確認してください', 'register_success' => '登録成功', 'register_success_verify' => '登録成功、メールコードログインで確認してください',
        'code_sent' => 'コードを送信しました、メールを確認してください', 'code_error' => 'コードが不正または期限切れです', 'current_password' => '現在のパスワード（変更時）', 'new_password' => '新しいパスワード', 'password_error' => '現在のパスワードが不正です', 'profile_updated' => 'プロフィールを更新しました', 'profile_password_updated' => 'プロフィールとパスワードを更新しました',
        'ticket_submitted' => 'チケットを送信しました', 'ticket_closed' => 'チケットをクローズしました', 'fill_title_content' => 'タイトルと内容を入力してください', 'ticket_not_exist' => 'チケットが存在しません', 'new_ticket_form' => '新規チケット', 'reply_placeholder' => '返信内容', 'close_ticket_confirm' => 'このチケットをクローズしますか？', 'back_to_list' => 'チケット一覧へ', 'ticket_records' => 'チケット履歴', 'view_detail' => '表示', 'ticket_question' => '問題の内容',
        'cat_technical' => '技術相談', 'cat_after_sales' => 'アフターセールス', 'cat_billing' => '請求', 'cat_complaint' => '苦情', 'cat_other' => 'その他',
        'feedback_submitted' => '送信成功、ありがとうございます', 'fill_content' => '内容を入力してください', 'official_reply' => '公式返信', 'official_tag' => '公式', 'visit_official' => 'ウェブサイト訪問', 'official_group' => 'グループチャット', 'international_site' => '国際版サイト',
        'product_detail' => '製品詳細', 'all_read_confirm' => 'すべて既読にしますか？', 'phone_label' => '電話番号',
    ],
    'ko' => [
        'home' => '홈', 'about' => '소개', 'company' => '회사 소개', 'products' => '제품',
        'partners' => '파트너', 'contact' => '문의하기', 'intl' => '국제 버전',
        'user_center' => '사용자 센터', 'admin' => '관리', 'login' => '로그인', 'logout' => '로그아웃',
        'register' => '회원가입', 'submit' => '제출', 'save' => '저장', 'cancel' => '취소',
        'edit' => '편집', 'delete' => '삭제', 'search' => '검색', 'phone' => '전화', 'email' => '이메일',
        'password' => '비밀번호', 'confirm_password' => '비밀번호 확인', 'nickname' => '닉네임', 'welcome' => '환영합니다',
        'back_to_top' => '맨 위로', 'online_support' => '지원', 'learn_more' => '자세히 보기',
        'view_products' => '제품 보기', 'detail' => '상세', 'copyright' => 'All Rights Reserved',
        'beian' => 'ICP', 'police' => 'Police Filing', 'sales_phone' => '영업 전화',
        'login_welcome' => '다시 오신 것을 환영합니다', 'login_subtitle' => '어운科技 사용자 센터 로그인',
        'register_account' => '계정 만들기', 'register_subtitle' => '가입 후 티켓 및 피드백 제출',
        'verify_login' => '이메일 코드 로그인', 'verify_subtitle' => '비밀번호 불필요, 5분 유효',
        'send_code' => '코드 전송', 'verify_code' => '인증 코드', 'my_tickets' => '내 티켓',
        'feedback' => '피드백', 'profile' => '프로필', 'notifications' => '알림',
        'no_notifications' => '알림 없음', 'mark_read' => '읽음 표시', 'system_notice' => '시스템 공지',
        'theme_light' => '라이트 모드', 'theme_dark' => '다크 모드', 'language' => '언어',
        'banner_default' => '어운科技에 오신 것을 환영합니다!',
        'products_title' => '비즈니스 및 제품', 'products_sub' => '클라우드, 보안, 기업 서비스의 풀스택 솔루션',
        'partners_title' => '다음 기업/조직과 협력합니다', 'map_title' => '글로벌 분포',
        'map_sub' => '글로벌 노드로 안정적이고 저지연 비즈니스 보장', 'cert_title' => '자격 증명',
        'cert_sub' => '컴플라이언스 경영, 신뢰할 수 있음', 'team_title' => '핵심 팀',
        'team_sub' => '세계 최고의 기술 및 인터넷 기업 출신', 'phone_consult' => '전화 상담',
        'later' => '나중에', 'welcome_to' => '환영합니다', 'quick_entry' => '빠른 접근',
        'new_ticket' => '새 티켓', 'ticket_title' => '제목', 'ticket_category' => '카테고리',
        'ticket_content' => '내용', 'status_open' => '처리 중', 'status_closed' => '종료',
        'reply' => '답변', 'close_ticket' => '티켓 종료', 'reopen' => '재개',
        'feedback_type' => '유형', 'suggestion' => '제안', 'report' => '신고',
        'complaint' => '불만', 'history' => '기록', 'contact_info' => '연락처 (선택)',
        'feedback_content' => '내용', 'submit_success' => '제출 완료, 피드백 감사합니다',
        'field_required' => '은(는) 필수입니다', 'no_image_tip' => '이미지가 없습니다. 관리자 페이지에서 업로드하세요.',
        'click_mask_close' => '오버레이 클릭하여 닫기', 'cert_preview' => '증명서 미리보기',
        'business_license' => '사업자등록증', 'ev_license' => '부가통신사업 허가증',
        'security_cert' => '정보보안 등급보호', 'trust_cert' => '신뢰할 수 있는 클라우드 인증',
        'issued_by' => '공상행정관리국 발급', 'telecom_license' => '통신 및 정보서비스 사업 허가',
        'level3_cert' => '3급 등급보호 인증', 'cloud_eval' => '클라우드 서비스 능력 평가',
        'about_title' => '어운 소개', 'company_title' => '회사 소개', 'contact_title' => '문의하기',
        'partners_title_page' => '파트너', 'products_title_page' => '제품',
        'company_name' => '회사명', 'company_short' => '약칭', 'company_address' => '주소',
        'company_phone' => '전화', 'company_group' => '그룹 채팅', 'company_intro' => '소개',
        'address' => '주소', 'select_language' => '언어 선택',
        'page_about' => '소개', 'page_company' => '회사 소개', 'page_contact' => '문의하기', 'page_partners' => '파트너', 'page_products' => '제품', 'page_login' => '로그인', 'page_register' => '회원가입', 'page_verify' => '이메일 코드 로그인',
        'about_sub' => '어운科技의 사명과 가치관 알아보기', 'company_sub' => '연혁 · 기업 문화 · 핵심 강점', 'contact_sub' => '함께 협력하기를 기대합니다', 'partners_sub' => '업계 리더들과 미래를 함께', 'products_sub' => '풀스택 클라우드 제품 및 솔루션',
        'your_name' => '이름', 'contact_email' => '연락처 이메일', 'message_content' => '메시지', 'submit_message' => '메시지 보내기', 'contact_success' => '메시지 감사합니다. 곧 연락드리겠습니다!', 'fill_complete' => '모든 필드를 입력해 주세요',
        'company_desc' => '는 글로벌 클라우드 컴퓨팅 및 디지털 서비스 제공업체입니다. 자체 데이터센터와 글로벌 파트너 네트워크를 통해 클라우드 서버, 베어메탈, CDN 가속, DDoS 보호, 기업 이메일, IDC 재무 시스템 라이선스를 원스톱으로 제공합니다.',
        'history_title' => '연혁', 'culture_title' => '기업 문화', 'advantages_title' => '핵심 강점', 'culture_desc' => '우리는 "고객 우선, 기술 주도, 글로벌 협력"의 가치관을 고수하며, 모든 기업이 안정적이고 안전하며 보편적인 클라우드 컴퓨팅을 누릴 수 있도록 노력합니다.',
        'global_network' => '글로벌 네트워크', 'security_protection' => '보안', 'support_247' => '24/7 지원', 'global_network_desc' => '다중 지역, 다중 통신사 백본, 스마트 스케줄링.', 'security_protection_desc' => 'T급 DDoS 방어 및 WAF.', 'support_247_desc' => '전문 팀 24시간 대응.',
        'password_login' => '비밀번호 로그인', 'code_login' => '이메일 코드 로그인', 'no_account' => '계정이 없나요?', 'register_now' => '회원가입', 'has_account' => '계정이 있나요?', 'login_now' => '로그인',
        'email_invalid' => '이메일 형식이 올바르지 않습니다', 'password_short' => '비밀번호는 6자 이상이어야 합니다', 'password_mismatch' => '비밀번호가 일치하지 않습니다', 'email_exists' => '이미 등록된 이메일입니다', 'login_success' => '로그인 성공', 'email_or_password_error' => '이메일 또는 비밀번호가 올바르지 않습니다', 'email_not_verified' => '이메일 미인증, 이메일 코드 로그인으로 인증하세요', 'register_success' => '가입 성공', 'register_success_verify' => '가입 성공, 이메일 코드 로그인으로 인증하세요',
        'code_sent' => '코드를 전송했습니다, 이메일을 확인하세요', 'code_error' => '코드가 올바르지 않거나 만료되었습니다', 'current_password' => '현재 비밀번호 (변경 시)', 'new_password' => '새 비밀번호', 'password_error' => '현재 비밀번호가 올바르지 않습니다', 'profile_updated' => '프로필이 업데이트되었습니다', 'profile_password_updated' => '프로필과 비밀번호가 업데이트되었습니다',
        'ticket_submitted' => '티켓이 제출되었습니다', 'ticket_closed' => '티켓이 종료되었습니다', 'fill_title_content' => '제목과 내용을 입력해 주세요', 'ticket_not_exist' => '티켓이 존재하지 않습니다', 'new_ticket_form' => '새 티켓', 'reply_placeholder' => '답변 내용', 'close_ticket_confirm' => '이 티켓을 종료하시겠습니까?', 'back_to_list' => '티켓 목록으로', 'ticket_records' => '티켓 기록', 'view_detail' => '보기', 'ticket_question' => '문제 설명',
        'cat_technical' => '기술 문의', 'cat_after_sales' => '사후 지원', 'cat_billing' => '결제', 'cat_complaint' => '불만', 'cat_other' => '기타',
        'feedback_submitted' => '제출 완료, 감사합니다', 'fill_content' => '내용을 입력해 주세요', 'official_reply' => '공식 답변', 'official_tag' => '공식', 'visit_official' => '웹사이트 방문', 'official_group' => '그룹 채팅', 'international_site' => '국제 사이트',
        'product_detail' => '제품 상세', 'all_read_confirm' => '모두 읽음으로 표시?', 'phone_label' => '전화번호',
    ],
    'zh-TW' => [
        'home' => '首頁', 'about' => '關於我們', 'company' => '公司簡介', 'products' => '產品介紹',
        'partners' => '合作夥伴', 'contact' => '聯絡我們', 'intl' => '國際版官網',
        'user_center' => '使用者中心', 'admin' => '後台', 'login' => '登入', 'logout' => '登出',
        'register' => '註冊', 'submit' => '提交', 'save' => '儲存', 'cancel' => '取消',
        'edit' => '編輯', 'delete' => '刪除', 'search' => '搜尋', 'phone' => '電話', 'email' => '信箱',
        'password' => '密碼', 'confirm_password' => '確認密碼', 'nickname' => '暱稱', 'welcome' => '歡迎',
        'back_to_top' => '返回頂部', 'online_support' => '線上客服', 'learn_more' => '立即了解',
        'view_products' => '查看產品', 'detail' => '了解詳情', 'copyright' => '版權所有',
        'beian' => '備案號', 'police' => '公安網備案號', 'sales_phone' => '銷售電話',
        'login_welcome' => '歡迎回來', 'login_subtitle' => '登入語雲科技使用者中心',
        'register_account' => '建立帳號', 'register_subtitle' => '註冊後即可提交工單與建議',
        'verify_login' => '信箱驗證碼登入', 'verify_subtitle' => '無需密碼，驗證碼 5 分鐘內有效',
        'send_code' => '發送驗證碼', 'verify_code' => '驗證碼', 'my_tickets' => '我的工單',
        'feedback' => '建議/檢舉', 'profile' => '個人資料', 'notifications' => '訊息通知',
        'no_notifications' => '暫無訊息', 'mark_read' => '標記已讀', 'system_notice' => '系統公告',
        'theme_light' => '淺色模式', 'theme_dark' => '深色模式', 'language' => '語言',
        'banner_default' => '歡迎來到語雲科技官網！',
        'products_title' => '業務與產品', 'products_sub' => '覆蓋雲端運算、網路安全、企業服務的全端解決方案',
        'partners_title' => '我們與以下企業 / 組織攜手共進', 'map_title' => '公司分佈',
        'map_sub' => '全球節點佈局，保障業務穩定低延遲', 'cert_title' => '資質證照',
        'cert_sub' => '合規經營，值得信賴', 'team_title' => '核心團隊',
        'team_sub' => '來自全球頂尖科技與網際網路企業', 'phone_consult' => '電話諮詢',
        'later' => '稍後再說', 'welcome_to' => '歡迎來到', 'quick_entry' => '快捷入口',
        'new_ticket' => '提交工單', 'ticket_title' => '標題', 'ticket_category' => '分類',
        'ticket_content' => '內容', 'status_open' => '處理中', 'status_closed' => '已關閉',
        'reply' => '回覆', 'close_ticket' => '關閉工單', 'reopen' => '重新開啟',
        'feedback_type' => '類型', 'suggestion' => '產品建議', 'report' => '違規檢舉',
        'complaint' => '投訴', 'history' => '歷史記錄', 'contact_info' => '聯絡方式（選填）',
        'feedback_content' => '內容', 'submit_success' => '提交成功，感謝您的回饋',
        'field_required' => '不能為空', 'no_image_tip' => '暫無圖片，請前往後台上傳資質證照。',
        'click_mask_close' => '點擊遮罩關閉', 'cert_preview' => '證照預覽',
        'business_license' => '營業執照', 'ev_license' => '電子加值服務產業證',
        'security_cert' => '資訊安全等級保護', 'trust_cert' => '可信雲服務認證',
        'issued_by' => '工商行政管理機關核發', 'telecom_license' => '電信與資訊服務業務經營許可',
        'level3_cert' => '三級等保認證', 'cloud_eval' => '雲端運算服務能力評估',
        'about_title' => '關於語雲', 'company_title' => '公司簡介', 'contact_title' => '聯絡我們',
        'partners_title_page' => '合作夥伴', 'products_title_page' => '產品介紹',
        'company_name' => '公司名稱', 'company_short' => '公司簡稱', 'company_address' => '公司地址',
        'company_phone' => '公司電話', 'company_group' => '官方群聊', 'company_intro' => '公司簡介',
        'address' => '地址', 'select_language' => '選擇語言',
        'page_about' => '關於我們', 'page_company' => '公司簡介', 'page_contact' => '聯絡我們', 'page_partners' => '合作夥伴', 'page_products' => '產品介紹', 'page_login' => '使用者登入', 'page_register' => '使用者註冊', 'page_verify' => '信箱驗證碼登入',
        'about_sub' => '了解語雲科技的使命與價值觀', 'company_sub' => '發展歷程 · 企業文化 · 核心優勢', 'contact_sub' => '期待與您攜手合作', 'partners_sub' => '攜手行業領袖，共建生態未來', 'products_sub' => '全端雲產品與數位化解決方案',
        'your_name' => '您的姓名', 'contact_email' => '聯絡信箱', 'message_content' => '留言內容', 'submit_message' => '提交留言', 'contact_success' => '感謝您的留言，我們會盡快與您聯絡！', 'fill_complete' => '請填寫完整資訊',
        'company_desc' => '是一家全球化雲端運算與數位化服務供應商。我們依託自建資料中心與全球合作夥伴網路，為企業客戶提供雲伺服器、裸金屬、CDN 加速、DDoS 防護、企業信箱以及 IDC 財務系統授權等一站式解決方案。',
        'history_title' => '發展歷程', 'culture_title' => '企業文化', 'advantages_title' => '核心優勢', 'culture_desc' => '我們堅持「客戶為先、技術驅動、全球協作」的價值觀，致力於讓每一家企業都能享受到穩定、安全、普惠的雲端運算能力。',
        'global_network' => '全球網路', 'security_protection' => '安全防護', 'support_247' => '7×24 支援', 'global_network_desc' => '多地區、多電信業者骨幹網路，智慧調度。', 'security_protection_desc' => 'T 級 DDoS 清洗與 Web 應用防火牆。', 'support_247_desc' => '專業技術團隊全天候回應。',
        'password_login' => '密碼登入', 'code_login' => '信箱驗證碼登入', 'no_account' => '還沒有帳號？', 'register_now' => '立即註冊', 'has_account' => '已有帳號？', 'login_now' => '立即登入',
        'email_invalid' => '信箱格式不正確', 'password_short' => '密碼至少 6 位', 'password_mismatch' => '兩次密碼不一致', 'email_exists' => '該信箱已註冊', 'login_success' => '登入成功', 'email_or_password_error' => '信箱或密碼錯誤', 'email_not_verified' => '信箱尚未驗證，請使用信箱驗證碼登入完成驗證', 'register_success' => '註冊成功', 'register_success_verify' => '註冊成功，請使用信箱驗證碼登入完成驗證',
        'code_sent' => '驗證碼已發送，請查收信箱', 'code_error' => '驗證碼錯誤或已過期', 'current_password' => '目前密碼（修改密碼時填寫）', 'new_password' => '新密碼', 'password_error' => '目前密碼錯誤', 'profile_updated' => '資料已更新', 'profile_password_updated' => '資料與密碼已更新',
        'ticket_submitted' => '工單已提交', 'ticket_closed' => '工單已關閉', 'fill_title_content' => '請填寫標題和內容', 'ticket_not_exist' => '工單不存在', 'new_ticket_form' => '提交新工單', 'reply_placeholder' => '回覆內容', 'close_ticket_confirm' => '確定關閉該工單？', 'back_to_list' => '返回工單列表', 'ticket_records' => '工單記錄', 'view_detail' => '查看', 'ticket_question' => '問題描述',
        'cat_technical' => '技術諮詢', 'cat_after_sales' => '售後問題', 'cat_billing' => '帳單疑問', 'cat_complaint' => '投訴建議', 'cat_other' => '其他',
        'feedback_submitted' => '提交成功，感謝您的回饋', 'fill_content' => '請填寫內容', 'official_reply' => '官方回覆', 'official_tag' => '官方', 'visit_official' => '訪問官網', 'official_group' => '官方群聊', 'international_site' => '國際版官網',
        'product_detail' => '產品詳情', 'all_read_confirm' => '全部標記為已讀？', 'phone_label' => '手機',
    ],
    'ru' => [
        'home' => 'Главная', 'about' => 'О нас', 'company' => 'О компании', 'products' => 'Продукты',
        'partners' => 'Партнёры', 'contact' => 'Контакты', 'intl' => 'Международная версия',
        'user_center' => 'Центр пользователя', 'admin' => 'Админ', 'login' => 'Вход', 'logout' => 'Выход',
        'register' => 'Регистрация', 'submit' => 'Отправить', 'save' => 'Сохранить', 'cancel' => 'Отмена',
        'edit' => 'Изменить', 'delete' => 'Удалить', 'search' => 'Поиск', 'phone' => 'Телефон', 'email' => 'Email',
        'password' => 'Пароль', 'confirm_password' => 'Подтвердите пароль', 'nickname' => 'Никнейм', 'welcome' => 'Добро пожаловать',
        'back_to_top' => 'Наверх', 'online_support' => 'Поддержка', 'learn_more' => 'Подробнее',
        'view_products' => 'Смотреть продукты', 'detail' => 'Подробности', 'copyright' => 'Все права защищены',
        'beian' => 'ICP', 'police' => 'Police Filing', 'sales_phone' => 'Отдел продаж',
        'login_welcome' => 'С возвращением', 'login_subtitle' => 'Вход в центр пользователя YuYun',
        'register_account' => 'Создать аккаунт', 'register_subtitle' => 'Зарегистрируйтесь для подачи заявок и отзывов',
        'verify_login' => 'Вход по коду email', 'verify_subtitle' => 'Без пароля, код действителен 5 минут',
        'send_code' => 'Отправить код', 'verify_code' => 'Код подтверждения', 'my_tickets' => 'Мои заявки',
        'feedback' => 'Отзыв', 'profile' => 'Профиль', 'notifications' => 'Уведомления',
        'no_notifications' => 'Нет уведомлений', 'mark_read' => 'Отметить прочитанным', 'system_notice' => 'Системное уведомление',
        'theme_light' => 'Светлая тема', 'theme_dark' => 'Тёмная тема', 'language' => 'Язык',
        'banner_default' => 'Добро пожаловать в YuYun Technology!',
        'products_title' => 'Бизнес и продукты', 'products_sub' => 'Полный стек решений: облако, безопасность, корпоративные сервисы',
        'partners_title' => 'Мы сотрудничаем со следующими компаниями и организациями', 'map_title' => 'Глобальное присутствие',
        'map_sub' => 'Глобальная сеть узлов для стабильности и низких задержек', 'cert_title' => 'Сертификаты',
        'cert_sub' => 'Комплаенс и надёжность', 'team_title' => 'Основная команда',
        'team_sub' => 'Из ведущих мировых технологических компаний', 'phone_consult' => 'Позвонить нам',
        'later' => 'Позже', 'welcome_to' => 'Добро пожаловать в', 'quick_entry' => 'Быстрый доступ',
        'new_ticket' => 'Новая заявка', 'ticket_title' => 'Заголовок', 'ticket_category' => 'Категория',
        'ticket_content' => 'Содержание', 'status_open' => 'Открыта', 'status_closed' => 'Закрыта',
        'reply' => 'Ответить', 'close_ticket' => 'Закрыть заявку', 'reopen' => 'Возобновить',
        'feedback_type' => 'Тип', 'suggestion' => 'Предложение', 'report' => 'Жалоба',
        'complaint' => 'Претензия', 'history' => 'История', 'contact_info' => 'Контакт (необязательно)',
        'feedback_content' => 'Содержание', 'submit_success' => 'Отправлено успешно, спасибо за отзыв',
        'field_required' => 'не может быть пустым', 'no_image_tip' => 'Нет изображения. Загрузите в админ-панели.',
        'click_mask_close' => 'Нажмите на overlay для закрытия', 'cert_preview' => 'Предпросмотр сертификата',
        'business_license' => 'Лицензия на деятельность', 'ev_license' => 'Лицензия доп. услуг',
        'security_cert' => 'Защита информации', 'trust_cert' => 'Сертификат доверенного облака',
        'issued_by' => 'Выдано торгово-промышленным управлением', 'telecom_license' => 'Лицензия на телекоммуникации',
        'level3_cert' => 'Сертификация уровня 3', 'cloud_eval' => 'Оценка возможностей облачных сервисов',
        'about_title' => 'О YuYun', 'company_title' => 'О компании', 'contact_title' => 'Контакты',
        'partners_title_page' => 'Партнёры', 'products_title_page' => 'Продукты',
        'company_name' => 'Название компании', 'company_short' => 'Краткое имя', 'company_address' => 'Адрес',
        'company_phone' => 'Телефон', 'company_group' => 'Групповой чат', 'company_intro' => 'Описание',
        'address' => 'Адрес', 'select_language' => 'Выбрать язык',
        'page_about' => 'О нас', 'page_company' => 'О компании', 'page_contact' => 'Контакты', 'page_partners' => 'Партнёры', 'page_products' => 'Продукты', 'page_login' => 'Вход', 'page_register' => 'Регистрация', 'page_verify' => 'Вход по коду email',
        'about_sub' => 'Узнайте о миссии и ценностях YuYun', 'company_sub' => 'История · Культура · Преимущества', 'contact_sub' => '期待 сотрудничество с вами', 'partners_sub' => 'С лидерами отрасли строим будущее', 'products_sub' => 'Полный стек облачных продуктов и решений',
        'your_name' => 'Ваше имя', 'contact_email' => 'Контактный email', 'message_content' => 'Сообщение', 'submit_message' => 'Отправить', 'contact_success' => 'Спасибо за сообщение, мы свяжемся с вами!', 'fill_complete' => 'Заполните все поля',
        'company_desc' => '— глобальный провайдер облачных и цифровых услуг. Опираясь на собственные дата-центры и глобальную сеть партнёров, мы предоставляем облачные серверы, bare metal, CDN, защиту от DDoS, корпоративную почту и лицензии IDC в комплексе.',
        'history_title' => 'История', 'culture_title' => 'Культура', 'advantages_title' => 'Преимущества', 'culture_desc' => 'Мы придерживаемся ценностей «клиент прежде всего, технологии, глобальное сотрудничество» и стремимся дать каждому бизнесу стабильные, безопасные и доступные облачные технологии.',
        'global_network' => 'Глобальная сеть', 'security_protection' => 'Безопасность', 'support_247' => 'Поддержка 24/7', 'global_network_desc' => 'Мультирегиональная магистраль, умная маршрутизация.', 'security_protection_desc' => 'DDoS-защита T-уровня и WAF.', 'support_247_desc' => 'Профессиональная команда 24/7.',
        'password_login' => 'Вход по паролю', 'code_login' => 'Вход по коду email', 'no_account' => 'Нет аккаунта?', 'register_now' => 'Регистрация', 'has_account' => 'Есть аккаунт?', 'login_now' => 'Войти',
        'email_invalid' => 'Неверный формат email', 'password_short' => 'Пароль не менее 6 символов', 'password_mismatch' => 'Пароли не совпадают', 'email_exists' => 'Email уже зарегистрирован', 'login_success' => 'Вход выполнен', 'email_or_password_error' => 'Неверный email или пароль', 'email_not_verified' => 'Email не подтверждён, используйте вход по коду', 'register_success' => 'Регистрация успешна', 'register_success_verify' => 'Зарегистрированы, подтвердите email через код',
        'code_sent' => 'Код отправлен, проверьте почту', 'code_error' => 'Код неверен или истёк', 'current_password' => 'Текущий пароль (для смены)', 'new_password' => 'Новый пароль', 'password_error' => 'Текущий пароль неверен', 'profile_updated' => 'Профиль обновлён', 'profile_password_updated' => 'Профиль и пароль обновлены',
        'ticket_submitted' => 'Заявка отправлена', 'ticket_closed' => 'Заявка закрыта', 'fill_title_content' => 'Заполните заголовок и содержание', 'ticket_not_exist' => 'Заявка не найдена', 'new_ticket_form' => 'Новая заявка', 'reply_placeholder' => 'Ответ', 'close_ticket_confirm' => 'Закрыть заявку?', 'back_to_list' => 'К списку заявок', 'ticket_records' => 'История заявок', 'view_detail' => 'Открыть', 'ticket_question' => 'Описание проблемы',
        'cat_technical' => 'Технический', 'cat_after_sales' => 'Поддержка', 'cat_billing' => 'Оплата', 'cat_complaint' => 'Жалоба', 'cat_other' => 'Другое',
        'feedback_submitted' => 'Отправлено, спасибо', 'fill_content' => 'Введите содержание', 'official_reply' => 'Официальный ответ', 'official_tag' => 'Официально', 'visit_official' => 'Сайт', 'official_group' => 'Чат', 'international_site' => 'Международный сайт',
        'product_detail' => 'О продукте', 'all_read_confirm' => 'Отметить все прочитанными?', 'phone_label' => 'Телефон',
    ],
    'fr' => [
        'home' => 'Accueil', 'about' => 'À propos', 'company' => 'Entreprise', 'products' => 'Produits',
        'partners' => 'Partenaires', 'contact' => 'Contact', 'intl' => 'Version internationale',
        'user_center' => 'Espace utilisateur', 'admin' => 'Admin', 'login' => 'Connexion', 'logout' => 'Déconnexion',
        'register' => 'Inscription', 'submit' => 'Envoyer', 'save' => 'Enregistrer', 'cancel' => 'Annuler',
        'edit' => 'Modifier', 'delete' => 'Supprimer', 'search' => 'Rechercher', 'phone' => 'Téléphone', 'email' => 'Email',
        'password' => 'Mot de passe', 'confirm_password' => 'Confirmer le mot de passe', 'nickname' => 'Pseudo', 'welcome' => 'Bienvenue',
        'back_to_top' => 'Haut de page', 'online_support' => 'Support', 'learn_more' => 'En savoir plus',
        'view_products' => 'Voir les produits', 'detail' => 'Détails', 'copyright' => 'Tous droits réservés',
        'beian' => 'ICP', 'police' => 'Police Filing', 'sales_phone' => 'Ventes',
        'login_welcome' => 'Bon retour', 'login_subtitle' => 'Connexion à l\'espace utilisateur YuYun',
        'register_account' => 'Créer un compte', 'register_subtitle' => 'Inscrivez-vous pour soumettre des tickets et des retours',
        'verify_login' => 'Connexion par code email', 'verify_subtitle' => 'Sans mot de passe, code valide 5 minutes',
        'send_code' => 'Envoyer le code', 'verify_code' => 'Code de vérification', 'my_tickets' => 'Mes tickets',
        'feedback' => 'Retour', 'profile' => 'Profil', 'notifications' => 'Notifications',
        'no_notifications' => 'Aucune notification', 'mark_read' => 'Marquer comme lu', 'system_notice' => 'Avis système',
        'theme_light' => 'Mode clair', 'theme_dark' => 'Mode sombre', 'language' => 'Langue',
        'banner_default' => 'Bienvenue chez YuYun Technology !',
        'products_title' => 'Entreprise & Produits', 'products_sub' => 'Solutions complètes : cloud, sécurité, services d\'entreprise',
        'partners_title' => 'Nous collaborons avec ces entreprises et organisations', 'map_title' => 'Présence mondiale',
        'map_sub' => 'Des nœuds mondiaux pour des opérations stables et à faible latence', 'cert_title' => 'Qualifications',
        'cert_sub' => 'Conformité et fiabilité', 'team_title' => 'Équipe principale',
        'team_sub' => 'Des meilleures entreprises technologiques mondiales', 'phone_consult' => 'Nous appeler',
        'later' => 'Plus tard', 'welcome_to' => 'Bienvenue chez', 'quick_entry' => 'Accès rapide',
        'new_ticket' => 'Nouveau ticket', 'ticket_title' => 'Titre', 'ticket_category' => 'Catégorie',
        'ticket_content' => 'Contenu', 'status_open' => 'Ouvert', 'status_closed' => 'Fermé',
        'reply' => 'Répondre', 'close_ticket' => 'Fermer le ticket', 'reopen' => 'Rouvrir',
        'feedback_type' => 'Type', 'suggestion' => 'Suggestion', 'report' => 'Signalement',
        'complaint' => 'Plainte', 'history' => 'Historique', 'contact_info' => 'Contact (facultatif)',
        'feedback_content' => 'Contenu', 'submit_success' => 'Envoyé avec succès, merci pour votre retour',
        'field_required' => 'ne peut pas être vide', 'no_image_tip' => 'Aucune image. Veuillez téléverser dans l\'admin.',
        'click_mask_close' => 'Cliquez sur l\'overlay pour fermer', 'cert_preview' => 'Aperçu du certificat',
        'business_license' => 'Licence commerciale', 'ev_license' => 'Licence de services à valeur ajoutée',
        'security_cert' => 'Protection de sécurité信息', 'trust_cert' => 'Certification cloud de confiance',
        'issued_by' => 'Délivré par l\'administration du commerce', 'telecom_license' => 'Licence de services télécoms',
        'level3_cert' => 'Certification niveau 3', 'cloud_eval' => 'Évaluation des services cloud',
        'about_title' => 'À propos de YuYun', 'company_title' => 'Profil de l\'entreprise', 'contact_title' => 'Contact',
        'partners_title_page' => 'Partenaires', 'products_title_page' => 'Produits',
        'company_name' => 'Nom de l\'entreprise', 'company_short' => 'Abréviation', 'company_address' => 'Adresse',
        'company_phone' => 'Téléphone', 'company_group' => 'Chat de groupe', 'company_intro' => 'Introduction',
        'address' => 'Adresse', 'select_language' => 'Choisir la langue',
        'page_about' => 'À propos', 'page_company' => 'Entreprise', 'page_contact' => 'Contact', 'page_partners' => 'Partenaires', 'page_products' => 'Produits', 'page_login' => 'Connexion', 'page_register' => 'Inscription', 'page_verify' => 'Connexion par code email',
        'about_sub' => 'Découvrez la mission et les valeurs de YuYun', 'company_sub' => 'Histoire · Culture · Atouts', 'contact_sub' => 'Au plaisir de collaborer avec vous', 'partners_sub' => 'Avec les leaders, construisons l\'avenir', 'products_sub' => 'Solutions cloud complètes',
        'your_name' => 'Votre nom', 'contact_email' => 'Email de contact', 'message_content' => 'Message', 'submit_message' => 'Envoyer', 'contact_success' => 'Merci pour votre message, nous vous contacterons !', 'fill_complete' => 'Veuillez remplir tous les champs',
        'company_desc' => 'est un fournisseur mondial de services cloud et numériques. Grâce à nos data centers et à notre réseau de partenaires, nous offrons serveurs cloud, bare metal, CDN, protection DDoS, messagerie et licences IDC en solution intégrée.',
        'history_title' => 'Histoire', 'culture_title' => 'Culture', 'advantages_title' => 'Atouts', 'culture_desc' => 'Nous portons les valeurs « client d\'abord, technologie, collaboration mondiale » et voulons que chaque entreprise profite d\'un cloud stable, sûr et accessible.',
        'global_network' => 'Réseau mondial', 'security_protection' => 'Sécurité', 'support_247' => 'Support 24/7', 'global_network_desc' => 'Backbone multi-régions, routage intelligent.', 'security_protection_desc' => 'Anti-DDoS niveau T et WAF.', 'support_247_desc' => 'Équipe pro disponible 24/7.',
        'password_login' => 'Connexion par mot de passe', 'code_login' => 'Connexion par code email', 'no_account' => 'Pas de compte ?', 'register_now' => 'Inscription', 'has_account' => 'Déjà un compte ?', 'login_now' => 'Connexion',
        'email_invalid' => 'Format d\'email invalide', 'password_short' => 'Mot de passe min. 6 caractères', 'password_mismatch' => 'Les mots de passe ne correspondent pas', 'email_exists' => 'Email déjà enregistré', 'login_success' => 'Connexion réussie', 'email_or_password_error' => 'Email ou mot de passe incorrect', 'email_not_verified' => 'Email non vérifié, utilisez le code email', 'register_success' => 'Inscription réussie', 'register_success_verify' => 'Inscrit, vérifiez via le code email',
        'code_sent' => 'Code envoyé, vérifiez votre email', 'code_error' => 'Code incorrect ou expiré', 'current_password' => 'Mot de passe actuel (pour modification)', 'new_password' => 'Nouveau mot de passe', 'password_error' => 'Mot de passe actuel incorrect', 'profile_updated' => 'Profil mis à jour', 'profile_password_updated' => 'Profil et mot de passe mis à jour',
        'ticket_submitted' => 'Ticket envoyé', 'ticket_closed' => 'Ticket fermé', 'fill_title_content' => 'Veuillez remplir le titre et le contenu', 'ticket_not_exist' => 'Ticket introuvable', 'new_ticket_form' => 'Nouveau ticket', 'reply_placeholder' => 'Réponse', 'close_ticket_confirm' => 'Fermer ce ticket ?', 'back_to_list' => 'Retour aux tickets', 'ticket_records' => 'Historique', 'view_detail' => 'Voir', 'ticket_question' => 'Description',
        'cat_technical' => 'Technique', 'cat_after_sales' => 'SAV', 'cat_billing' => 'Facturation', 'cat_complaint' => 'Plainte', 'cat_other' => 'Autre',
        'feedback_submitted' => 'Envoyé, merci', 'fill_content' => 'Veuillez saisir le contenu', 'official_reply' => 'Réponse officielle', 'official_tag' => 'Officiel', 'visit_official' => 'Site web', 'official_group' => 'Chat', 'international_site' => 'Site international',
        'product_detail' => 'Détails produit', 'all_read_confirm' => 'Tout marquer comme lu ?', 'phone_label' => 'Téléphone',
    ],
    'de' => [
        'home' => 'Startseite', 'about' => 'Über uns', 'company' => 'Unternehmen', 'products' => 'Produkte',
        'partners' => 'Partner', 'contact' => 'Kontakt', 'intl' => 'Internationale Version',
        'user_center' => 'Benutzerzentrum', 'admin' => 'Admin', 'login' => 'Anmelden', 'logout' => 'Abmelden',
        'register' => 'Registrieren', 'submit' => 'Absenden', 'save' => 'Speichern', 'cancel' => 'Abbrechen',
        'edit' => 'Bearbeiten', 'delete' => 'Löschen', 'search' => 'Suchen', 'phone' => 'Telefon', 'email' => 'E-Mail',
        'password' => 'Passwort', 'confirm_password' => 'Passwort bestätigen', 'nickname' => 'Spitzname', 'welcome' => 'Willkommen',
        'back_to_top' => 'Nach oben', 'online_support' => 'Support', 'learn_more' => 'Mehr erfahren',
        'view_products' => 'Produkte ansehen', 'detail' => 'Details', 'copyright' => 'Alle Rechte vorbehalten',
        'beian' => 'ICP', 'police' => 'Police Filing', 'sales_phone' => 'Vertrieb',
        'login_welcome' => 'Willkommen zurück', 'login_subtitle' => 'Anmeldung im YuYun Benutzerzentrum',
        'register_account' => 'Konto erstellen', 'register_subtitle' => 'Registrieren Sie sich, um Tickets & Feedback zu senden',
        'verify_login' => 'E-Mail-Code-Anmeldung', 'verify_subtitle' => 'Kein Passwort nötig, Code 5 Min gültig',
        'send_code' => 'Code senden', 'verify_code' => 'Bestätigungscode', 'my_tickets' => 'Meine Tickets',
        'feedback' => 'Feedback', 'profile' => 'Profil', 'notifications' => 'Benachrichtigungen',
        'no_notifications' => 'Keine Benachrichtigungen', 'mark_read' => 'Als gelesen markieren', 'system_notice' => 'Systemhinweis',
        'theme_light' => 'Heller Modus', 'theme_dark' => 'Dunkler Modus', 'language' => 'Sprache',
        'banner_default' => 'Willkommen bei YuYun Technology!',
        'products_title' => 'Business & Produkte', 'products_sub' => 'Full-Stack-Lösungen für Cloud, Sicherheit & Unternehmensservices',
        'partners_title' => 'Wir arbeiten mit diesen Unternehmen & Organisationen zusammen', 'map_title' => 'Globale Präsenz',
        'map_sub' => 'Globale Knoten für stabile und latenzarme Geschäfte', 'cert_title' => 'Qualifikationen',
        'cert_sub' => 'Compliance & Vertrauen', 'team_title' => 'Kernteam',
        'team_sub' => 'Von den besten globalen Tech- & Internetunternehmen', 'phone_consult' => 'Anrufen',
        'later' => 'Später', 'welcome_to' => 'Willkommen bei', 'quick_entry' => 'Schnellzugriff',
        'new_ticket' => 'Neues Ticket', 'ticket_title' => 'Titel', 'ticket_category' => 'Kategorie',
        'ticket_content' => 'Inhalt', 'status_open' => 'Offen', 'status_closed' => 'Geschlossen',
        'reply' => 'Antworten', 'close_ticket' => 'Ticket schließen', 'reopen' => 'Wieder öffnen',
        'feedback_type' => 'Typ', 'suggestion' => 'Vorschlag', 'report' => 'Meldung',
        'complaint' => 'Beschwerde', 'history' => 'Verlauf', 'contact_info' => 'Kontakt (optional)',
        'feedback_content' => 'Inhalt', 'submit_success' => 'Erfolgreich gesendet, danke für Ihr Feedback',
        'field_required' => 'darf nicht leer sein', 'no_image_tip' => 'Kein Bild. Bitte im Admin hochladen.',
        'click_mask_close' => 'Overlay zum Schließen klicken', 'cert_preview' => 'Zertifikat-Vorschau',
        'business_license' => 'Gewerbeausweis', 'ev_license' => 'Mehrwertdienst-Lizenz',
        'security_cert' => 'Informationssicherheit', 'trust_cert' => 'Vertrauenswürdige Cloud-Zertifizierung',
        'issued_by' => 'Von der Handelsverwaltung ausgestellt', 'telecom_license' => 'Telekommunikationslizenz',
        'level3_cert' => 'Level 3 Zertifizierung', 'cloud_eval' => 'Cloud-Service-Bewertung',
        'about_title' => 'Über YuYun', 'company_title' => 'Unternehmensprofil', 'contact_title' => 'Kontakt',
        'partners_title_page' => 'Partner', 'products_title_page' => 'Produkte',
        'company_name' => 'Firmenname', 'company_short' => 'Abkürzung', 'company_address' => 'Adresse',
        'company_phone' => 'Telefon', 'company_group' => 'Gruppenchat', 'company_intro' => 'Einführung',
        'address' => 'Adresse', 'select_language' => 'Sprache wählen',
        'page_about' => 'Über uns', 'page_company' => 'Unternehmen', 'page_contact' => 'Kontakt', 'page_partners' => 'Partner', 'page_products' => 'Produkte', 'page_login' => 'Anmelden', 'page_register' => 'Registrieren', 'page_verify' => 'E-Mail-Code-Anmeldung',
        'about_sub' => 'Erfahren Sie mehr über YuYuns Mission und Werte', 'company_sub' => 'Geschichte · Kultur · Vorteile', 'contact_sub' => 'Wir freuen uns auf die Zusammenarbeit', 'partners_sub' => 'Mit Branchenführern die Zukunft gestalten', 'products_sub' => 'Vollständige Cloud-Lösungen',
        'your_name' => 'Ihr Name', 'contact_email' => 'Kontakt-E-Mail', 'message_content' => 'Nachricht', 'submit_message' => 'Senden', 'contact_success' => 'Danke für Ihre Nachricht, wir melden uns bald!', 'fill_complete' => 'Bitte alle Felder ausfüllen',
        'company_desc' => 'ist ein globaler Anbieter von Cloud- und Digitaldiensten. Mit eigenen Rechenzentren und einem globalen Partnernetzwerk bieten wir Cloud-Server, Bare Metal, CDN, DDoS-Schutz, Unternehmens-E-Mail und IDC-Lizenzen aus einer Hand.',
        'history_title' => 'Geschichte', 'culture_title' => 'Kultur', 'advantages_title' => 'Vorteile', 'culture_desc' => 'Wir vertreten die Werte «Kunde zuerst, Technologie, globale Zusammenarbeit» und wollen, dass jedes Unternehmen von stabilem, sicherem und zugänglichem Cloud-Computing profitiert.',
        'global_network' => 'Globales Netzwerk', 'security_protection' => 'Sicherheit', 'support_247' => '24/7 Support', 'global_network_desc' => 'Multi-Region-Backbone, intelligente Steuerung.', 'security_protection_desc' => 'T-Klasse DDoS-Schutz und WAF.', 'support_247_desc' => 'Professionelles Team rund um die Uhr.',
        'password_login' => 'Passwort-Anmeldung', 'code_login' => 'E-Mail-Code-Anmeldung', 'no_account' => 'Kein Konto?', 'register_now' => 'Registrieren', 'has_account' => 'Konto vorhanden?', 'login_now' => 'Anmelden',
        'email_invalid' => 'Ungültiges E-Mail-Format', 'password_short' => 'Passwort min. 6 Zeichen', 'password_mismatch' => 'Passwörter stimmen nicht überein', 'email_exists' => 'E-Mail bereits registriert', 'login_success' => 'Anmeldung erfolgreich', 'email_or_password_error' => 'E-Mail oder Passwort falsch', 'email_not_verified' => 'E-Mail nicht verifiziert, nutzen Sie den E-Mail-Code', 'register_success' => 'Registrierung erfolgreich', 'register_success_verify' => 'Registriert, verifizieren Sie per E-Mail-Code',
        'code_sent' => 'Code gesendet, prüfen Sie Ihre E-Mail', 'code_error' => 'Code falsch oder abgelaufen', 'current_password' => 'Aktuelles Passwort (bei Änderung)', 'new_password' => 'Neues Passwort', 'password_error' => 'Aktuelles Passwort falsch', 'profile_updated' => 'Profil aktualisiert', 'profile_password_updated' => 'Profil und Passwort aktualisiert',
        'ticket_submitted' => 'Ticket gesendet', 'ticket_closed' => 'Ticket geschlossen', 'fill_title_content' => 'Bitte Titel und Inhalt ausfüllen', 'ticket_not_exist' => 'Ticket nicht gefunden', 'new_ticket_form' => 'Neues Ticket', 'reply_placeholder' => 'Antwort', 'close_ticket_confirm' => 'Dieses Ticket schließen?', 'back_to_list' => 'Zurück zur Liste', 'ticket_records' => 'Ticketverlauf', 'view_detail' => 'Ansehen', 'ticket_question' => 'Beschreibung',
        'cat_technical' => 'Technik', 'cat_after_sales' => 'Kundendienst', 'cat_billing' => 'Abrechnung', 'cat_complaint' => 'Beschwerde', 'cat_other' => 'Sonstiges',
        'feedback_submitted' => 'Gesendet, danke', 'fill_content' => 'Bitte Inhalt eingeben', 'official_reply' => 'Offizielle Antwort', 'official_tag' => 'Offiziell', 'visit_official' => 'Website', 'official_group' => 'Chat', 'international_site' => 'Internationale Website',
        'product_detail' => 'Produktdetails', 'all_read_confirm' => 'Alle als gelesen markieren?', 'phone_label' => 'Telefon',
    ],
];

function __(string $key): string {
    global $translations, $currentLang;
    return $translations[$currentLang][$key] ?? ($translations['en'][$key] ?? ($translations['zh'][$key] ?? $key));
}

function langUrl(string $lang): string {
    $url = $_SERVER['REQUEST_URI'] ?? '/';
    $url = preg_replace('/([?&])lang=[^&]+&?/', '$1', $url);
    $url = rtrim($url, '?&');
    $sep = strpos($url, '?') === false ? '?' : '&';
    return $url . $sep . 'lang=' . urlencode($lang);
}
