<?php
return [
  'articles' => [
    [
      'id' => 'A001',
      'title' => '平台六一八活动公告',
      'category' => '平台公告',
      'isTop' => true,
      'status' => 'published',
      'publishAt' => '2026-06-18 10:00',
    ],
    [
      'id' => 'A002',
      'title' => '关于调整结算周期的通知',
      'category' => '结算公告',
      'isTop' => false,
      'status' => 'published',
      'publishAt' => '2026-06-20 16:00',
    ],
    [
      'id' => 'A003',
      'title' => '新手入驻指南',
      'category' => '帮助文档',
      'isTop' => false,
      'status' => 'draft',
      'publishAt' => '-',
    ],
  ],
  'coupons' => [
    [
      'id' => 'CO001',
      'batch' => 'BATCH0618',
      'type' => 'fixed',
      'value' => 10,
      'threshold' => 50,
      'total' => 1000,
      'received' => 856,
      'status' => 'active',
    ],
    [
      'id' => 'CO002',
      'batch' => 'BATCHNEW',
      'type' => 'percent',
      'value' => 20,
      'threshold' => 100,
      'total' => 500,
      'received' => 500,
      'status' => 'expired',
    ],
  ],
  'skus' => [
    [
      'id' => 'S001',
      'name' => '入门版',
      'bandwidth' => '10Mbps',
      'flow' => '100GB/月',
      'domains' => 1,
      'ccLevel' => '基础',
      'price' => 9.9,
    ],
    [
      'id' => 'S002',
      'name' => '标准版',
      'bandwidth' => '50Mbps',
      'flow' => '500GB/月',
      'domains' => 3,
      'ccLevel' => '标准',
      'price' => 49,
    ],
    [
      'id' => 'S003',
      'name' => '专业版',
      'bandwidth' => '200Mbps',
      'flow' => '2TB/月',
      'domains' => 10,
      'ccLevel' => '高级',
      'price' => 199,
    ],
    [
      'id' => 'S004',
      'name' => '企业版',
      'bandwidth' => '1Gbps',
      'flow' => '10TB/月',
      'domains' => 50,
      'ccLevel' => '企业',
      'price' => 999,
    ],
  ],
  'packages' => [
    [
      'id' => 'PKG01',
      'name' => '入门版',
      'flow' => '100GB',
      'bandwidth' => '10Mbps',
      'domains' => 1,
      'price' => 9.90,
      'period' => '月',
    ],
    [
      'id' => 'PKG02',
      'name' => '标准版',
      'flow' => '500GB',
      'bandwidth' => '50Mbps',
      'domains' => 3,
      'price' => 49.00,
      'period' => '月',
    ],
    [
      'id' => 'PKG03',
      'name' => '专业版',
      'flow' => '2TB',
      'bandwidth' => '200Mbps',
      'domains' => 10,
      'price' => 199.00,
      'period' => '月',
    ],
    [
      'id' => 'PKG04',
      'name' => '企业版',
      'flow' => '10TB',
      'bandwidth' => '1Gbps',
      'domains' => 50,
      'price' => 999.00,
      'period' => '月',
    ],
  ],
  'merchants' => [
    [
      'id' => 'M001',
      'avatar' => '速',
      'shopName' => '极速云',
      'phone' => '138****1234',
      'registerAt' => '2026-01-10',
      'deposit' => 5000,
      'status' => 'normal',
    ],
    [
      'id' => 'M002',
      'avatar' => '蓝',
      'shopName' => '蓝海防护',
      'phone' => '139****5678',
      'registerAt' => '2026-02-15',
      'deposit' => 3000,
      'status' => 'normal',
    ],
    [
      'id' => 'M003',
      'avatar' => '店',
      'shopName' => '站点卫士',
      'phone' => '137****9012',
      'registerAt' => '2026-03-20',
      'deposit' => 0,
      'status' => 'pending',
    ],
    [
      'id' => 'M004',
      'avatar' => '云',
      'shopName' => '云盾科技',
      'phone' => '136****3456',
      'registerAt' => '2026-04-12',
      'deposit' => 2000,
      'status' => 'banned',
    ],
  ],
  'users' => [
    [
      'id' => 'U001',
      'nickname' => 'user_9527',
      'phone' => '138****1234',
      'level' => 'VIP1',
      'group' => '默认分组',
      'registerAt' => '2026-01-10',
      'status' => 'normal',
    ],
    [
      'id' => 'U002',
      'nickname' => 'user_3344',
      'phone' => '139****5678',
      'level' => '普通会员',
      'group' => '默认分组',
      'registerAt' => '2026-02-15',
      'status' => 'normal',
    ],
    [
      'id' => 'U003',
      'nickname' => 'user_7788',
      'phone' => '137****9012',
      'level' => 'VIP2',
      'group' => '高价值用户',
      'registerAt' => '2026-03-20',
      'status' => 'banned',
    ],
    [
      'id' => 'U004',
      'nickname' => 'user_1122',
      'phone' => '136****3456',
      'level' => '普通会员',
      'group' => '默认分组',
      'registerAt' => '2026-04-12',
      'status' => 'normal',
    ],
  ],
  'orders' => [
    [
      'id' => 'O202606280001',
      'buyer' => 'user_9527',
      'merchant' => '极速云',
      'product' => '企业高防CDN',
      'amount' => 299,
      'status' => 'paid',
      'createdAt' => '2026-06-28 10:23',
    ],
    [
      'id' => 'O202606280002',
      'buyer' => 'user_3344',
      'merchant' => '蓝海防护',
      'product' => '基础CDN加速',
      'amount' => 59,
      'status' => 'pending',
      'createdAt' => '2026-06-28 09:45',
    ],
    [
      'id' => 'O202606280003',
      'buyer' => 'user_7788',
      'merchant' => '站点卫士',
      'product' => '全球加速Pro',
      'amount' => 199,
      'status' => 'refunded',
      'createdAt' => '2026-06-27 22:10',
    ],
    [
      'id' => 'O202606280004',
      'buyer' => 'user_1122',
      'merchant' => '云盾科技',
      'product' => '游戏盾专业版',
      'amount' => 599,
      'status' => 'closed',
      'createdAt' => '2026-06-27 18:33',
    ],
  ],
  'categories' => [
    [
      'id' => 'C1',
      'name' => 'CDN 加速',
      'parentId' => null,
      'sort' => 1,
    ],
    [
      'id' => 'C2',
      'name' => '高防 CDN',
      'parentId' => null,
      'sort' => 2,
    ],
    [
      'id' => 'C3',
      'name' => '游戏盾',
      'parentId' => null,
      'sort' => 3,
    ],
    [
      'id' => 'C4',
      'name' => '全球加速',
      'parentId' => null,
      'sort' => 4,
    ],
    [
      'id' => 'C5',
      'name' => '企业级',
      'parentId' => 'C1',
      'sort' => 1,
    ],
  ],
  'adSlots' => [
    [
      'id' => 'AD001',
      'name' => 'PC 首页轮播',
      'position' => '电脑端首页顶部',
      'size' => '1920x400',
      'status' => 'on',
    ],
    [
      'id' => 'AD002',
      'name' => '购卡页横幅',
      'position' => '购卡页中部',
      'size' => '1200x200',
      'status' => 'on',
    ],
    [
      'id' => 'AD003',
      'name' => 'APP 启动页',
      'position' => 'APP 启动页',
      'size' => '750x1334',
      'status' => 'off',
    ],
  ],
  'complaints' => [
    [
      'id' => 'CP001',
      'orderId' => 'O202606280003',
      'plaintiff' => 'user_7788',
      'defendant' => '站点卫士',
      'reason' => '未到账',
      'status' => 'pending',
      'createdAt' => '2026-06-28 09:00',
    ],
    [
      'id' => 'CP002',
      'orderId' => 'O202606270056',
      'plaintiff' => 'user_3344',
      'defendant' => '蓝海防护',
      'reason' => '商品与描述不符',
      'status' => 'resolved',
      'createdAt' => '2026-06-27 14:20',
    ],
    [
      'id' => 'CP003',
      'orderId' => 'O202606260012',
      'plaintiff' => 'user_9527',
      'defendant' => '极速云',
      'reason' => '无法访问',
      'status' => 'rejected',
      'createdAt' => '2026-06-26 11:30',
    ],
  ],
  'gateways' => [
    [
      'id' => 'GW001',
      'name' => '支付宝官方',
      'channel' => 'alipay',
      'fee' => 0.6,
      'enabled' => true,
      'isDefault' => true,
    ],
    [
      'id' => 'GW002',
      'name' => '微信支付商户号',
      'channel' => 'wxpay',
      'fee' => 0.6,
      'enabled' => true,
      'isDefault' => false,
    ],
    [
      'id' => 'GW003',
      'name' => '易支付-通道A',
      'channel' => 'epay',
      'fee' => 2,
      'enabled' => true,
      'isDefault' => false,
    ],
    [
      'id' => 'GW004',
      'name' => 'USDT-TRC20',
      'channel' => 'usdt',
      'fee' => 1,
      'enabled' => false,
      'isDefault' => false,
    ],
  ],
  'nodes' => [
    [
      'id' => 'N001',
      'name' => '北京电信-01',
      'ip' => '1.1.1.1',
      'region' => '华北',
      'isp' => '电信',
      'type' => '自建',
      'health' => 'healthy',
      'enabled' => true,
      'latency' => 12,
      'uptime' => '99.99%',
    ],
    [
      'id' => 'N002',
      'name' => '上海联通-01',
      'ip' => '2.2.2.2',
      'region' => '华东',
      'isp' => '联通',
      'type' => '自建',
      'health' => 'healthy',
      'enabled' => true,
      'latency' => 15,
      'uptime' => '99.95%',
    ],
    [
      'id' => 'N003',
      'name' => '广州移动-01',
      'ip' => '3.3.3.3',
      'region' => '华南',
      'isp' => '移动',
      'type' => '公开节点',
      'health' => 'warning',
      'enabled' => true,
      'latency' => 45,
      'uptime' => '98.50%',
    ],
    [
      'id' => 'N004',
      'name' => 'Cloudflare-HK',
      'ip' => 'cf-hk.example.com',
      'region' => '海外',
      'isp' => 'BGP',
      'type' => 'Cloudflare',
      'health' => 'healthy',
      'enabled' => true,
      'latency' => 28,
      'uptime' => '99.90%',
    ],
    [
      'id' => 'N005',
      'name' => '成都电信-01',
      'ip' => '4.4.4.4',
      'region' => '西南',
      'isp' => '电信',
      'type' => '自建',
      'health' => 'offline',
      'enabled' => false,
      'latency' => 0,
      'uptime' => '0.00%',
    ],
  ],
  'products' => [
    [
      'id' => 'P001',
      'name' => '基础CDN加速',
      'type' => 'CDN',
      'nodePool' => '公开节点池A',
      'priceRange' => '¥9.90 - ¥99.00',
      'status' => 'on',
    ],
    [
      'id' => 'P002',
      'name' => '企业高防CDN',
      'type' => '高防CDN',
      'nodePool' => '高防节点池B',
      'priceRange' => '¥299.00 - ¥2999.00',
      'status' => 'on',
    ],
    [
      'id' => 'P003',
      'name' => '游戏盾专业版',
      'type' => '游戏盾',
      'nodePool' => '游戏专用池C',
      'priceRange' => '¥599.00 - ¥5999.00',
      'status' => 'off',
    ],
    [
      'id' => 'P004',
      'name' => '全球加速Pro',
      'type' => '全球加速',
      'nodePool' => 'Cloudflare池',
      'priceRange' => '¥199.00 - ¥1999.00',
      'status' => 'on',
    ],
  ],
  'inviteCodes' => [
    [
      'id' => 'I001',
      'code' => 'INVITE2026A',
      'maxUses' => 100,
      'usedCount' => 32,
      'expiry' => '2026-12-31',
      'status' => 'active',
    ],
    [
      'id' => 'I002',
      'code' => 'VIP888',
      'maxUses' => 50,
      'usedCount' => 50,
      'expiry' => '2026-06-01',
      'status' => 'expired',
    ],
    [
      'id' => 'I003',
      'code' => 'TEST001',
      'maxUses' => 10,
      'usedCount' => 2,
      'expiry' => '2026-12-31',
      'status' => 'disabled',
    ],
  ],
  'userGroups' => [
    [
      'id' => 'G1',
      'name' => '默认分组',
      'userCount' => 4820,
    ],
    [
      'id' => 'G2',
      'name' => '高价值用户',
      'userCount' => 356,
    ],
    [
      'id' => 'G3',
      'name' => '渠道引流用户',
      'userCount' => 128,
    ],
  ],
  'userLevels' => [
    [
      'id' => 'L1',
      'name' => '普通会员',
      'minAmount' => 0,
      'discount' => 1,
    ],
    [
      'id' => 'L2',
      'name' => 'VIP1',
      'minAmount' => 500,
      'discount' => 0.95,
    ],
    [
      'id' => 'L3',
      'name' => 'VIP2',
      'minAmount' => 2000,
      'discount' => 0.88,
    ],
    [
      'id' => 'L4',
      'name' => 'VIP3',
      'minAmount' => 5000,
      'discount' => 0.8,
    ],
  ],
  'realnameRecords' => [
    [
      'id' => 'R001',
      'userId' => 'U001',
      'name' => '张三',
      'idCard' => '11010119900101****',
      'phone' => '138****1234',
      'status' => 'approved',
      'submittedAt' => '2026-06-20 10:00',
    ],
    [
      'id' => 'R002',
      'userId' => 'U002',
      'name' => '李四',
      'idCard' => '31010119900202****',
      'phone' => '139****5678',
      'status' => 'pending',
      'submittedAt' => '2026-06-27 14:30',
    ],
    [
      'id' => 'R003',
      'userId' => 'U003',
      'name' => '王五',
      'idCard' => '44010119900303****',
      'phone' => '137****9012',
      'status' => 'rejected',
      'submittedAt' => '2026-06-25 09:15',
    ],
  ],
  'roles' => [
    [
      'id' => 'R001',
      'name' => '超级管理员',
      'description' => '拥有全部权限',
      'permissions' => [
        '*',
      ],
      'userCount' => 1,
    ],
    [
      'id' => 'R002',
      'name' => '运营专员',
      'description' => '负责商户、订单、用户日常运营',
      'permissions' => [
        'merchants',
        'orders',
        'users',
        'complaints',
      ],
      'userCount' => 3,
    ],
    [
      'id' => 'R003',
      'name' => '财务人员',
      'description' => '负责结算、对账、网关配置',
      'permissions' => [
        'finance',
        'settlement',
        'payments',
      ],
      'userCount' => 2,
    ],
    [
      'id' => 'R004',
      'name' => '客服',
      'description' => '处理投诉、过白、实名审核',
      'permissions' => [
        'complaints',
        'whitelist',
        'user-realname',
      ],
      'userCount' => 4,
    ],
  ],
  'backupRecords' => [
    [
      'id' => 'B001',
      'name' => '全量备份-20260628-020000',
      'size' => '1.2GB',
      'type' => 'auto',
      'status' => 'success',
      'createdAt' => '2026-06-28 02:00:00',
    ],
    [
      'id' => 'B002',
      'name' => '数据库备份-20260627-020000',
      'size' => '860MB',
      'type' => 'auto',
      'status' => 'success',
      'createdAt' => '2026-06-27 02:00:00',
    ],
    [
      'id' => 'B003',
      'name' => '手动备份-20260626',
      'size' => '1.1GB',
      'type' => 'manual',
      'status' => 'success',
      'createdAt' => '2026-06-26 15:30:00',
    ],
    [
      'id' => 'B004',
      'name' => '全量备份-20260625-020000',
      'size' => '1.0GB',
      'type' => 'auto',
      'status' => 'failed',
      'createdAt' => '2026-06-25 02:00:00',
    ],
  ],
  'sites' => [
    [
      'id' => '1',
      'name' => '官网加速',
      'domain' => 'www.example.com',
      'template' => 'PC-01',
      'products' => 4,
      'nodes' => 12,
      'status' => 'running',
      'createdAt' => '2026-01-15',
    ],
    [
      'id' => '2',
      'name' => '商城防护',
      'domain' => 'shop.example.com',
      'template' => 'PC-02',
      'products' => 6,
      'nodes' => 8,
      'status' => 'running',
      'createdAt' => '2026-02-20',
    ],
    [
      'id' => '3',
      'name' => '博客加速',
      'domain' => 'blog.demo.com',
      'template' => 'M-01',
      'products' => 2,
      'nodes' => 4,
      'status' => 'pending',
      'createdAt' => '2026-03-10',
    ],
    [
      'id' => '4',
      'name' => '游戏盾',
      'domain' => 'game.xxx.com',
      'template' => 'PC-03',
      'products' => 3,
      'nodes' => 16,
      'status' => 'stopped',
      'createdAt' => '2026-04-05',
    ],
    [
      'id' => '5',
      'name' => 'API网关',
      'domain' => 'api.xxx.com',
      'template' => 'M-02',
      'products' => 1,
      'nodes' => 6,
      'status' => 'running',
      'createdAt' => '2026-05-18',
    ],
  ],
  'myPackages' => [
    [
      'id' => 'MP001',
      'name' => '标准版',
      'flow' => '500GB',
      'bandwidth' => '50Mbps',
      'domains' => 3,
      'expireAt' => '2026-12-31',
      'status' => 'active',
    ],
    [
      'id' => 'MP002',
      'name' => '专业版',
      'flow' => '2TB',
      'bandwidth' => '200Mbps',
      'domains' => 10,
      'expireAt' => '2027-01-15',
      'status' => 'active',
    ],
    [
      'id' => 'MP003',
      'name' => '入门版',
      'flow' => '100GB',
      'bandwidth' => '10Mbps',
      'domains' => 1,
      'expireAt' => '2026-05-31',
      'status' => 'expired',
    ],
  ],
  'bOrders' => [
    [
      'id' => 'O202606280001',
      'product' => '企业高防CDN',
      'amount' => 299,
      'status' => 'paid',
      'createdAt' => '2026-06-28 10:23',
      'paidAt' => '2026-06-28 10:25',
      'packageId' => 'PKG03',
      'period' => '1个月',
    ],
    [
      'id' => 'O202606270088',
      'product' => '全球加速Pro',
      'amount' => 199,
      'status' => 'paid',
      'createdAt' => '2026-06-27 15:40',
      'paidAt' => '2026-06-27 15:42',
      'packageId' => 'PKG02',
      'period' => '1个月',
    ],
    [
      'id' => 'O202606260056',
      'product' => '标准版套餐',
      'amount' => 49,
      'status' => 'refunded',
      'createdAt' => '2026-06-26 09:15',
      'paidAt' => '2026-06-26 09:16',
      'packageId' => 'PKG01',
      'period' => '1个月',
    ],
    [
      'id' => 'O202606250042',
      'product' => '专业版套餐',
      'amount' => 199,
      'status' => 'paid',
      'createdAt' => '2026-06-25 14:30',
      'paidAt' => '2026-06-25 14:32',
      'packageId' => 'PKG02',
      'period' => '3个月',
    ],
    [
      'id' => 'O202606240031',
      'product' => '入门版套餐',
      'amount' => 9.9,
      'status' => 'pending',
      'createdAt' => '2026-06-24 11:10',
      'packageId' => 'PKG01',
      'period' => '1个月',
    ],
    [
      'id' => 'O202606230028',
      'product' => '企业版套餐',
      'amount' => 999,
      'status' => 'cancelled',
      'createdAt' => '2026-06-23 16:50',
      'packageId' => 'PKG04',
      'period' => '1个月',
    ],
  ],
  'invoices' => [
    [
      'id' => 'INV20260628001',
      'orderId' => 'O202606280001',
      'amount' => 299,
      'status' => 'issued',
      'type' => 'company',
      'title' => '云盾科技有限公司',
      'taxId' => '91310101MA1G812345',
      'items' => [
        [
          'name' => '企业高防CDN（1个月）',
          'quantity' => 1,
          'unitPrice' => 299,
          'amount' => 299,
        ],
      ],
      'createdAt' => '2026-06-28 10:30',
      'issuedAt' => '2026-06-28 10:35',
    ],
    [
      'id' => 'INV20260627001',
      'orderId' => 'O202606270088',
      'amount' => 199,
      'status' => 'pending',
      'type' => 'personal',
      'title' => '张三',
      'items' => [
        [
          'name' => '全球加速Pro（1个月）',
          'quantity' => 1,
          'unitPrice' => 199,
          'amount' => 199,
        ],
      ],
      'createdAt' => '2026-06-27 16:00',
    ],
  ],
  'whitelistRecords' => [
    [
      'id' => 'W001',
      'domain' => 'www.shop-a.com',
      'purpose' => '电商站点加速',
      'icp' => '京ICP备123456号',
      'status' => 'approved',
      'createdAt' => '2026-06-25',
    ],
    [
      'id' => 'W002',
      'domain' => 'blog.demo-b.com',
      'purpose' => '个人博客',
      'icp' => '-',
      'status' => 'pending',
      'createdAt' => '2026-06-27',
    ],
    [
      'id' => 'W003',
      'domain' => 'api.game-c.com',
      'purpose' => '游戏API',
      'icp' => '沪ICP备654321号',
      'status' => 'rejected',
      'createdAt' => '2026-06-26',
      'reason' => '资料不完整',
    ],
  ],
  'financeRecords' => [
    [
      'id' => 'F001',
      'type' => 'income',
      'amount' => 1299,
      'balance' => 12850.65,
      'desc' => '订单 O202606280001 分润',
      'createdAt' => '2026-06-28 10:25',
    ],
    [
      'id' => 'F002',
      'type' => 'withdraw',
      'amount' => -5000,
      'balance' => 11551.65,
      'desc' => '提现至支付宝',
      'createdAt' => '2026-06-27 16:00',
    ],
    [
      'id' => 'F003',
      'type' => 'expense',
      'amount' => -299,
      'balance' => 16551.65,
      'desc' => '套餐续费',
      'createdAt' => '2026-06-26 09:12',
    ],
    [
      'id' => 'F004',
      'type' => 'frozen',
      'amount' => -200,
      'balance' => 16850.65,
      'desc' => '异常订单冻结',
      'createdAt' => '2026-06-25 14:33',
    ],
  ],
  'settlementRecords' => [
    [
      'id' => 'SET001',
      'merchant' => '极速云',
      'cycle' => 'T+1',
      'amount' => 4820,
      'fee' => 48.2,
      'status' => 'settled',
      'time' => '2026-06-28 10:00',
    ],
    [
      'id' => 'SET002',
      'merchant' => '蓝海防护',
      'cycle' => 'T+1',
      'amount' => 3150.5,
      'fee' => 31.51,
      'status' => 'settled',
      'time' => '2026-06-27 10:00',
    ],
    [
      'id' => 'SET003',
      'merchant' => '站点卫士',
      'cycle' => 'T+7',
      'amount' => 1200,
      'fee' => 12,
      'status' => 'pending',
      'time' => '2026-06-28 09:00',
    ],
  ],
  'commissionRecords' => [
    [
      'id' => 'C001',
      'agent' => '一级代理-小张',
      'orderId' => 'O202606280001',
      'amount' => 29.9,
      'status' => 'settled',
      'createdAt' => '2026-06-28 10:30',
    ],
    [
      'id' => 'C002',
      'agent' => '二级代理-阿强',
      'orderId' => 'O202606280002',
      'amount' => 5.9,
      'status' => 'pending',
      'createdAt' => '2026-06-28 09:50',
    ],
    [
      'id' => 'C003',
      'agent' => '一级代理-小美',
      'orderId' => 'O202606270056',
      'amount' => 19.9,
      'status' => 'settled',
      'createdAt' => '2026-06-27 15:00',
    ],
  ],
  'operationLogs' => [
    [
      'id' => 'L001',
      'operator' => 'admin',
      'module' => '商户管理',
      'action' => '审核通过',
      'detail' => '通过商户「云盾科技」入驻申请',
      'ip' => '192.168.1.10',
      'createdAt' => '2026-06-28 11:20:05',
    ],
    [
      'id' => 'L002',
      'operator' => 'admin',
      'module' => '商品管理',
      'action' => '下架商品',
      'detail' => '下架商品「游戏盾专业版」',
      'ip' => '192.168.1.10',
      'createdAt' => '2026-06-28 10:15:33',
    ],
    [
      'id' => 'L003',
      'operator' => 'admin',
      'module' => '财务管理',
      'action' => '手动结算',
      'detail' => '为「极速云」发起手动结算 ¥4820.00',
      'ip' => '192.168.1.12',
      'createdAt' => '2026-06-28 09:50:18',
    ],
    [
      'id' => 'L004',
      'operator' => 'admin',
      'module' => '系统设置',
      'action' => '修改费率',
      'detail' => '修改默认分组费率为 2.0%',
      'ip' => '192.168.1.10',
      'createdAt' => '2026-06-27 16:40:22',
    ],
  ],
  'apiDocs' => [
    [
      'id' => 'A001',
      'method' => 'POST',
      'path' => '/api/v1/sites',
      'name' => '创建站点',
      'desc' => '创建新的 CDN 站点',
      'group' => '站点',
    ],
    [
      'id' => 'A002',
      'method' => 'GET',
      'path' => '/api/v1/sites',
      'name' => '站点列表',
      'desc' => '获取当前商户的站点列表',
      'group' => '站点',
    ],
    [
      'id' => 'A003',
      'method' => 'PUT',
      'path' => '/api/v1/sites/:id',
      'name' => '更新站点',
      'desc' => '更新站点配置',
      'group' => '站点',
    ],
    [
      'id' => 'A004',
      'method' => 'DELETE',
      'path' => '/api/v1/sites/:id',
      'name' => '删除站点',
      'desc' => '删除指定站点',
      'group' => '站点',
    ],
    [
      'id' => 'A005',
      'method' => 'POST',
      'path' => '/api/v1/orders',
      'name' => '创建订单',
      'desc' => '创建套餐购买订单',
      'group' => '订单',
    ],
    [
      'id' => 'A006',
      'method' => 'GET',
      'path' => '/api/v1/orders',
      'name' => '订单列表',
      'desc' => '获取订单列表',
      'group' => '订单',
    ],
    [
      'id' => 'A007',
      'method' => 'POST',
      'path' => '/api/v1/whitelist',
      'name' => '过白申请',
      'desc' => '提交域名过白申请',
      'group' => '过白',
    ],
    [
      'id' => 'A008',
      'method' => 'GET',
      'path' => '/api/v1/finance/records',
      'name' => '资金流水',
      'desc' => '获取资金流水记录',
      'group' => '财务',
    ],
  ],
  'notifications' => [
    [
      'id' => 'NT001',
      'title' => '新商户入驻待审核',
      'content' => '商户「云盾科技」提交入驻申请，请及时处理。',
      'type' => 'system',
      'read' => false,
      'createdAt' => '2026-06-28 11:20',
      'link' => '/s/merchant-audit',
    ],
    [
      'id' => 'NT002',
      'title' => '域名过白申请被驳回',
      'content' => '您提交的 api.game-c.com 过白申请已被驳回，原因：资料不完整。',
      'type' => 'alert',
      'read' => false,
      'createdAt' => '2026-06-28 10:05',
      'link' => '/b/whitelist',
    ],
    [
      'id' => 'NT003',
      'title' => '收到新订单 O202606280001',
      'content' => '用户 user_9527 购买了企业高防CDN，金额 ¥299.00。',
      'type' => 'order',
      'read' => true,
      'createdAt' => '2026-06-28 10:23',
      'link' => '/s/orders',
    ],
    [
      'id' => 'NT004',
      'title' => '结算单 SET001 已打款',
      'content' => '您的 T+1 结算单 ¥4820.00 已通过支付宝打款。',
      'type' => 'finance',
      'read' => true,
      'createdAt' => '2026-06-28 09:30',
      'link' => '/b/finance',
    ],
    [
      'id' => 'NT005',
      'title' => '节点池高防B 延迟告警',
      'content' => '节点池高防B 平均延迟超过 200ms，请关注。',
      'type' => 'alert',
      'read' => true,
      'createdAt' => '2026-06-27 22:15',
      'link' => '/s/nodes',
    ],
  ],
  'dailyStats' => [
    [
      'date' => '06-22',
      'revenue' => 18200,
      'orders' => 420,
      'users' => 320,
      'merchants' => 12,
    ],
    [
      'date' => '06-23',
      'revenue' => 21500,
      'orders' => 510,
      'users' => 380,
      'merchants' => 15,
    ],
    [
      'date' => '06-24',
      'revenue' => 19800,
      'orders' => 460,
      'users' => 290,
      'merchants' => 10,
    ],
    [
      'date' => '06-25',
      'revenue' => 24300,
      'orders' => 580,
      'users' => 450,
      'merchants' => 18,
    ],
    [
      'date' => '06-26',
      'revenue' => 22100,
      'orders' => 520,
      'users' => 410,
      'merchants' => 14,
    ],
    [
      'date' => '06-27',
      'revenue' => 28900,
      'orders' => 680,
      'users' => 520,
      'merchants' => 22,
    ],
    [
      'date' => '06-28',
      'revenue' => 26400,
      'orders' => 610,
      'users' => 480,
      'merchants' => 19,
    ],
  ],
  'merchantStats' => [
    [
      'merchant' => '极速云',
      'revenue' => 482900,
      'orders' => 1250,
      'avgOrderValue' => 386.32,
      'growth' => 12.5,
    ],
    [
      'merchant' => '蓝海防护',
      'revenue' => 391200,
      'orders' => 980,
      'avgOrderValue' => 399.18,
      'growth' => 8.3,
    ],
    [
      'merchant' => '站点卫士',
      'revenue' => 284500,
      'orders' => 720,
      'avgOrderValue' => 395.14,
      'growth' => -2.1,
    ],
    [
      'merchant' => '云盾科技',
      'revenue' => 198300,
      'orders' => 510,
      'avgOrderValue' => 388.82,
      'growth' => 5.7,
    ],
    [
      'merchant' => '安全链',
      'revenue' => 165000,
      'orders' => 420,
      'avgOrderValue' => 392.86,
      'growth' => 15.2,
    ],
  ],
  'userGrowthStats' => [
    [
      'date' => '06-22',
      'newUsers' => 120,
      'activeUsers' => 4520,
      'paidUsers' => 380,
    ],
    [
      'date' => '06-23',
      'newUsers' => 132,
      'activeUsers' => 4610,
      'paidUsers' => 395,
    ],
    [
      'date' => '06-24',
      'newUsers' => 101,
      'activeUsers' => 4580,
      'paidUsers' => 402,
    ],
    [
      'date' => '06-25',
      'newUsers' => 134,
      'activeUsers' => 4720,
      'paidUsers' => 418,
    ],
    [
      'date' => '06-26',
      'newUsers' => 90,
      'activeUsers' => 4690,
      'paidUsers' => 410,
    ],
    [
      'date' => '06-27',
      'newUsers' => 230,
      'activeUsers' => 4920,
      'paidUsers' => 450,
    ],
    [
      'date' => '06-28',
      'newUsers' => 210,
      'activeUsers' => 5100,
      'paidUsers' => 465,
    ],
  ],
  'agents' => [
    [
      'id' => 'A001',
      'name' => '总代理-老李',
      'parent' => null,
      'level' => 1,
      'commission' => 15,
    ],
    [
      'id' => 'A002',
      'name' => '一级代理-小张',
      'parent' => 'A001',
      'level' => 2,
      'commission' => 10,
    ],
    [
      'id' => 'A003',
      'name' => '二级代理-阿强',
      'parent' => 'A002',
      'level' => 3,
      'commission' => 8,
    ],
    [
      'id' => 'A004',
      'name' => '一级代理-小美',
      'parent' => 'A001',
      'level' => 2,
      'commission' => 10,
    ],
  ],
  'agentProducts' => [
    [
      'id' => 'AP001',
      'name' => '基础CDN加速-代理版',
      'source' => '极速云',
      'costPrice' => 8,
      'retailPrice' => 12,
      'status' => 'on',
    ],
    [
      'id' => 'AP002',
      'name' => '企业高防CDN-代理版',
      'source' => '蓝海防护',
      'costPrice' => 250,
      'retailPrice' => 299,
      'status' => 'on',
    ],
    [
      'id' => 'AP003',
      'name' => '全球加速Pro-代理版',
      'source' => '站点卫士',
      'costPrice' => 180,
      'retailPrice' => 199,
      'status' => 'pending',
    ],
  ],
  'pcTemplates' => [
    [
      'id' => 'PC-01',
      'name' => '企业官网风格',
      'type' => 'pc',
    ],
    [
      'id' => 'PC-02',
      'name' => '科技深蓝风格',
      'type' => 'pc',
    ],
    [
      'id' => 'PC-03',
      'name' => '极简白风格',
      'type' => 'pc',
    ],
  ],
  'mobileTemplates' => [
    [
      'id' => 'M-01',
      'name' => '移动端标准版',
      'type' => 'mobile',
    ],
    [
      'id' => 'M-02',
      'name' => '移动端深色版',
      'type' => 'mobile',
    ],
    [
      'id' => 'M-03',
      'name' => '移动端渐变版',
      'type' => 'mobile',
    ],
    [
      'id' => 'M-04',
      'name' => '移动端卡片版',
      'type' => 'mobile',
    ],
  ],
  'cardTemplates' => [
    [
      'id' => 'CARD-01',
      'name' => '经典购卡页',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-02',
      'name' => '暗色游戏风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-03',
      'name' => '清新电商风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-04',
      'name' => '极简科技风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-05',
      'name' => '促销节日风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-06',
      'name' => '会员专享风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-07',
      'name' => '直播带货风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-08',
      'name' => '企业采购风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-09',
      'name' => '教育课程风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-10',
      'name' => '云服务风',
      'type' => 'card',
    ],
    [
      'id' => 'CARD-11',
      'name' => 'DIY 自定义',
      'type' => 'card',
    ],
  ],
  'luckyNumbers' => [
    [
      'id' => 'N001',
      'number' => '888888',
      'price' => 88,
      'sold' => false,
    ],
    [
      'id' => 'N002',
      'number' => '666666',
      'price' => 66,
      'sold' => true,
    ],
    [
      'id' => 'N003',
      'number' => '168888',
      'price' => 48,
      'sold' => false,
    ],
    [
      'id' => 'N004',
      'number' => '5201314',
      'price' => 128,
      'sold' => false,
    ],
    [
      'id' => 'N005',
      'number' => '999999',
      'price' => 99,
      'sold' => false,
    ],
  ],
];
